USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH; 

-- TASK 1: ENVIRONMENT SETUP & RAW TELEMETRY INGESTION
CREATE DATABASE IF NOT EXISTS CLEANROOM_SHARED_DB;
USE DATABASE CLEANROOM_SHARED_DB;

CREATE SCHEMA IF NOT EXISTS PARTNER_TELEMETRY;
USE SCHEMA PARTNER_TELEMETRY;

CREATE OR REPLACE FILE FORMAT JSON_FORMAT
    TYPE = 'JSON'
    STRIP_OUTER_ARRAY = FALSE;

CREATE OR REPLACE STAGE STG_PARTNER_TELEMETRY
    FILE_FORMAT = JSON_FORMAT;
    
CREATE OR REPLACE TABLE RAW_RETAIL_TRANSACTIONS (
    RAW_DATA VARIANT
);

CREATE OR REPLACE TABLE RAW_AD_EXPOSURES (
    RAW_DATA VARIANT
);

COPY INTO RAW_RETAIL_TRANSACTIONS
FROM @STG_PARTNER_TELEMETRY/bronze_retail_transactions.json
FILE_FORMAT = (FORMAT_NAME = JSON_FORMAT)
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO RAW_AD_EXPOSURES
FROM @STG_PARTNER_TELEMETRY/bronze_ad_exposures.json
FILE_FORMAT = (FORMAT_NAME = JSON_FORMAT)
ON_ERROR = 'ABORT_STATEMENT';

CREATE OR REPLACE TABLE BRONZE_RETAIL_TRANSACTIONS AS
SELECT
    RAW_DATA:pos_id::STRING           AS POS_ID,
    RAW_DATA:timestamp::TIMESTAMP_NTZ AS TIMESTAMP,
    RAW_DATA:hashed_email::STRING     AS HASHED_EMAIL,
    RAW_DATA:store_id::STRING         AS STORE_ID,
    RAW_DATA:cpg_brand::STRING        AS CPG_BRAND,
    RAW_DATA:basket_value::NUMBER(10,2) AS BASKET_VALUE,
    RAW_DATA:loyalty_tier::STRING     AS LOYALTY_TIER
FROM RAW_RETAIL_TRANSACTIONS;

CREATE OR REPLACE TABLE BRONZE_AD_EXPOSURES AS
SELECT
    RAW_DATA:ad_id::STRING            AS AD_ID,
    RAW_DATA:timestamp::TIMESTAMP_NTZ AS TIMESTAMP,
    RAW_DATA:hashed_email::STRING     AS HASHED_EMAIL,
    RAW_DATA:campaign_name::STRING    AS CAMPAIGN_NAME,
    RAW_DATA:channel::STRING          AS CHANNEL
FROM RAW_AD_EXPOSURES;

SELECT COUNT(*) AS TOTAL_RETAIL_RECORDS FROM BRONZE_RETAIL_TRANSACTIONS;

-- TASK 2: SILVER CLEAN ROOM OVERLAP & AGGREGATION LAYER
CREATE OR REPLACE TABLE SILVER_ATTRIBUTION_MATCH AS
SELECT
    pos.POS_ID,
    pos.STORE_ID,
    ad.CAMPAIGN_NAME,
    ad.CHANNEL,
    pos.BASKET_VALUE,
    DATEDIFF('hour', ad.TIMESTAMP, pos.TIMESTAMP) AS CONVERSION_HOURS
FROM BRONZE_RETAIL_TRANSACTIONS pos
JOIN BRONZE_AD_EXPOSURES ad
    ON pos.HASHED_EMAIL = ad.HASHED_EMAIL;

SELECT * FROM SILVER_ATTRIBUTION_MATCH
ORDER BY POS_ID;

-- TASK 3: AGGREGATE-ONLY DIFFERENTIAL PRIVACY VIEW (CLEAN ROOM GOVERNANCE)
CREATE OR REPLACE SECURE VIEW SECURE_GOLD_CAMPAIGN_ATTRIBUTION_PERFORMANCE AS
WITH FIRST_TOUCH AS (
    SELECT
        CAMPAIGN_NAME,
        CHANNEL,
        ROW_NUMBER() OVER (PARTITION BY CAMPAIGN_NAME ORDER BY TIMESTAMP ASC) AS RN
    FROM BRONZE_AD_EXPOSURES
)
SELECT
    s.CAMPAIGN_NAME,
    ft.CHANNEL,                              
    COUNT(DISTINCT s.POS_ID)   AS CONVERTED_USER_COUNT,
    SUM(s.BASKET_VALUE)        AS TOTAL_ATTRIBUTED_SALES,
    ROUND(AVG(s.BASKET_VALUE),2)        AS AVG_BASKET_VALUE
FROM SILVER_ATTRIBUTION_MATCH s
JOIN FIRST_TOUCH ft
    ON s.CAMPAIGN_NAME = ft.CAMPAIGN_NAME
   AND ft.RN = 1
GROUP BY s.CAMPAIGN_NAME, ft.CHANNEL
HAVING COUNT(DISTINCT s.POS_ID) >= 2;

SELECT * FROM SECURE_GOLD_CAMPAIGN_ATTRIBUTION_PERFORMANCE
ORDER BY CAMPAIGN_NAME, CHANNEL;

-- TASK 4: SECURE DATA SHARE CREATION & PRIVILEGE ASSIGNMENT
CREATE OR REPLACE SHARE SHARE_CPG_PARTNER_ANALYTICS;

GRANT USAGE ON DATABASE CLEANROOM_SHARED_DB
    TO SHARE SHARE_CPG_PARTNER_ANALYTICS;

GRANT USAGE ON SCHEMA CLEANROOM_SHARED_DB.PARTNER_TELEMETRY
    TO SHARE SHARE_CPG_PARTNER_ANALYTICS;

GRANT SELECT ON VIEW CLEANROOM_SHARED_DB.PARTNER_TELEMETRY.SECURE_GOLD_CAMPAIGN_ATTRIBUTION_PERFORMANCE
    TO SHARE SHARE_CPG_PARTNER_ANALYTICS;

SHOW SHARES LIKE 'SHARE_CPG_PARTNER_ANALYTICS';

-- TASK 5: PROVISIONING A READER ACCOUNT FOR NON-SNOWFLAKE PARTNERS
CREATE MANAGED ACCOUNT CPG_READER_ACCT_01
    ADMIN_NAME      = 'cpg_reader_admin'
    ADMIN_PASSWORD  = 'ChangeMe_Str0ngPwd!'
    TYPE            = READER
    COMMENT         = 'Managed reader account for CPG ad-tech partner - no native Snowflake deployment';

ALTER SHARE SHARE_CPG_PARTNER_ANALYTICS
    ADD ACCOUNTS = XWHRFAG.CPG_READER_ACCT_01;

SHOW MANAGED ACCOUNTS LIKE 'CPG_READER_ACCT_01';

CREATE OR REPLACE RESOURCE MONITOR RM_CPG_READER
    WITH CREDIT_QUOTA = 5
    FREQUENCY = MONTHLY
    START_TIMESTAMP = IMMEDIATELY
    TRIGGERS ON 80 PERCENT DO NOTIFY
             ON 100 PERCENT DO SUSPEND;

CREATE OR REPLACE WAREHOUSE CPG_READER_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    RESOURCE_MONITOR = RM_CPG_READER;

-- TASK 6: END-TO-END CLEAN ROOM RECONCILIATION & COMPLIANCE CHECK
WITH SILVER_TOTAL AS (
    SELECT SUM(BASKET_VALUE) AS SILVER_MATCH_VAL
    FROM SILVER_ATTRIBUTION_MATCH
),
GOLD_TOTAL AS (
    SELECT SUM(TOTAL_ATTRIBUTED_SALES) AS GOLD_SHARED_VAL
    FROM SECURE_GOLD_CAMPAIGN_ATTRIBUTION_PERFORMANCE
),
PII_CHECK AS (
    SELECT COUNT(*) AS PII_COLUMN_COUNT
    FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = 'PARTNER_TELEMETRY'
      AND TABLE_NAME = 'SECURE_GOLD_CAMPAIGN_ATTRIBUTION_PERFORMANCE'
      AND COLUMN_NAME ILIKE '%HASHED_EMAIL%'
)
SELECT
    s.SILVER_MATCH_VAL,
    g.GOLD_SHARED_VAL,
    IFF(p.PII_COLUMN_COUNT = 0, FALSE, TRUE)                       AS PII_EXPOSURE_FLAG,
    IFF(s.SILVER_MATCH_VAL = g.GOLD_SHARED_VAL, TRUE, FALSE)       AS RECONCILED_FLAG
FROM SILVER_TOTAL s, GOLD_TOTAL g, PII_CHECK p;