-- Task 1 — Create Snowflake Database and Schema
CREATE WAREHOUSE P8_WH;

CREATE DATABASE P8_DB;

CREATE SCHEMA P8_DB.P8_SCHEMA;

USE WAREHOUSE P8_WH;

USE DATABASE P8_DB;

USE SCHEMA P8_SCHEMA;

-- Task 2 — Create Initial Customer Dimension
CREATE TABLE DIM_CUSTOMER (
    CUSTOMER_KEY   INT AUTOINCREMENT,
    CUSTOMER_ID    INT,
    CUSTOMER_NAME  VARCHAR,
    CITY           VARCHAR,
    STATE          VARCHAR,
    MEMBERSHIP     VARCHAR,
    SEGMENT        VARCHAR
);

-- Task 3 — Load Initial Customer Data
CREATE FILE FORMAT CSV_FORMAT
    TYPE = 'CSV'
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"';

CREATE STAGE P8_STAGE FILE_FORMAT = CSV_FORMAT;

COPY INTO DIM_CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, CITY, STATE, MEMBERSHIP, SEGMENT)
FROM @P8_STAGE/customers_initial.csv;

-- Task 4 — Display Initial Customer Dimension
SELECT 
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT
FROM DIM_CUSTOMER
ORDER BY CUSTOMER_ID;

-- Task 5 — Load Customer Updates
CREATE TABLE CUSTOMER_UPDATES (
    CUSTOMER_ID    INT,
    CUSTOMER_NAME  VARCHAR,
    CITY           VARCHAR,
    STATE          VARCHAR,
    MEMBERSHIP     VARCHAR,
    SEGMENT        VARCHAR
);

COPY INTO CUSTOMER_UPDATES (CUSTOMER_ID, CUSTOMER_NAME, CITY, STATE, MEMBERSHIP, SEGMENT)
FROM @P8_STAGE/customer_updates.csv;

-- Task 6 — Identify Changed Customers
SELECT 
    d.CUSTOMER_ID,
    d.CITY AS OLD_CITY,
    u.CITY AS NEW_CITY,
    d.MEMBERSHIP AS OLD_MEMBERSHIP,
    u.MEMBERSHIP AS NEW_MEMBERSHIP
FROM DIM_CUSTOMER d
JOIN CUSTOMER_UPDATES u
    ON d.CUSTOMER_ID = u.CUSTOMER_ID
WHERE d.CITY <> u.CITY
   OR d.STATE <> u.STATE
   OR d.MEMBERSHIP <> u.MEMBERSHIP
   OR d.SEGMENT <> u.SEGMENT
ORDER BY d.CUSTOMER_ID;

-- Task 7 — Identify Attribute Changes
SELECT d.CUSTOMER_ID, 'CITY' AS ATTRIBUTE, d.CITY AS OLD_VALUE, u.CITY AS NEW_VALUE
FROM DIM_CUSTOMER d JOIN CUSTOMER_UPDATES u ON d.CUSTOMER_ID = u.CUSTOMER_ID
WHERE d.CITY <> u.CITY

UNION ALL

SELECT d.CUSTOMER_ID, 'STATE', d.STATE, u.STATE
FROM DIM_CUSTOMER d JOIN CUSTOMER_UPDATES u ON d.CUSTOMER_ID = u.CUSTOMER_ID
WHERE d.STATE <> u.STATE

UNION ALL

SELECT d.CUSTOMER_ID, 'MEMBERSHIP', d.MEMBERSHIP, u.MEMBERSHIP
FROM DIM_CUSTOMER d JOIN CUSTOMER_UPDATES u ON d.CUSTOMER_ID = u.CUSTOMER_ID
WHERE d.MEMBERSHIP <> u.MEMBERSHIP

UNION ALL

SELECT d.CUSTOMER_ID, 'SEGMENT', d.SEGMENT, u.SEGMENT
FROM DIM_CUSTOMER d JOIN CUSTOMER_UPDATES u ON d.CUSTOMER_ID = u.CUSTOMER_ID
WHERE d.SEGMENT <> u.SEGMENT

ORDER BY CUSTOMER_ID,
    CASE ATTRIBUTE
        WHEN 'CITY' THEN 1
        WHEN 'STATE' THEN 2
        WHEN 'MEMBERSHIP' THEN 3
        WHEN 'SEGMENT' THEN 4
    END;

-- Task 8 — Demonstrate the SCD Problem
UPDATE DIM_CUSTOMER d
SET 
    CITY       = u.CITY,
    STATE      = u.STATE,
    MEMBERSHIP = u.MEMBERSHIP,
    SEGMENT    = u.SEGMENT
FROM CUSTOMER_UPDATES u
WHERE d.CUSTOMER_ID = u.CUSTOMER_ID;

-- Task 9 — Display the Updated Dimension
SELECT 
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT
FROM DIM_CUSTOMER
ORDER BY CUSTOMER_ID;

-- Task 10 — Demonstrate Historical Data Loss
SELECT 
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP
FROM DIM_CUSTOMER
WHERE CUSTOMER_ID = 101;
