CREATE WAREHOUSE IF NOT EXISTS P19B_WH;
USE WAREHOUSE P19B_WH;

CREATE DATABASE IF NOT EXISTS P19B_DB;
USE DATABASE P19B_DB;

CREATE SCHEMA IF NOT EXISTS PROJECT_19B;
USE SCHEMA PROJECT_19B;

CREATE OR REPLACE FILE FORMAT FF_CSV_STANDARD
    TYPE = 'CSV'
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    NULL_IF = ('NULL', '')
    EMPTY_FIELD_AS_NULL = TRUE;

CREATE OR REPLACE STAGE STG_PROJECT_19B
    FILE_FORMAT = FF_CSV_STANDARD;

-- TASK 1: Factless Coverage Table Setup
CREATE OR REPLACE TABLE STG_DOCTOR_ROSTER (
    SHIFT_DATE      DATE,
    DOCTOR_ID       VARCHAR(20),
    DEPARTMENT_ID   VARCHAR(20),
    SHIFT_TYPE      VARCHAR(20)
);

COPY INTO STG_DOCTOR_ROSTER
FROM @STG_PROJECT_19B/raw_doctor_roster.csv
FILE_FORMAT = (FORMAT_NAME = FF_CSV_STANDARD)
ON_ERROR = 'ABORT_STATEMENT';

CREATE OR REPLACE TABLE FACTLESS_STAFF_COVERAGE (
    SHIFT_DATE      DATE,
    DOCTOR_ID       VARCHAR(20),
    DEPARTMENT_ID   VARCHAR(20),
    SHIFT_TYPE      VARCHAR(20)
);

INSERT INTO FACTLESS_STAFF_COVERAGE
SELECT SHIFT_DATE, DOCTOR_ID, DEPARTMENT_ID, SHIFT_TYPE
FROM STG_DOCTOR_ROSTER;

SELECT COUNT(*) AS TOTAL_ROSTER_ROWS
FROM FACTLESS_STAFF_COVERAGE;

-- TASK 2: Factless Coverage Analysis Query
WITH DEPTS_ON_DATE AS (
    SELECT DISTINCT DEPARTMENT_ID
    FROM FACTLESS_STAFF_COVERAGE
    WHERE SHIFT_DATE = '2026-08-20'
),
NIGHT_SHIFTS AS (
    SELECT DEPARTMENT_ID, COUNT(*) AS NIGHT_SHIFT_COUNT
    FROM FACTLESS_STAFF_COVERAGE
    WHERE SHIFT_DATE = '2026-08-20'
      AND SHIFT_TYPE = 'NIGHT'
    GROUP BY DEPARTMENT_ID
)
SELECT
    d.DEPARTMENT_ID,
    COALESCE(n.NIGHT_SHIFT_COUNT, 0) AS NIGHT_SHIFT_COUNT
FROM DEPTS_ON_DATE d
LEFT JOIN NIGHT_SHIFTS n
    ON d.DEPARTMENT_ID = n.DEPARTMENT_ID
WHERE COALESCE(n.NIGHT_SHIFT_COUNT, 0) = 0;

-- TASK 3: Patient Lifecycle Accumulating Snapshot Table
CREATE OR REPLACE TABLE STG_PATIENT_JOURNEY (
    ENCOUNTER_ID    VARCHAR(20),
    PATIENT_ID      VARCHAR(20),
    TRIAGE_DATE     DATE,
    ADMISSION_DATE  DATE,
    DISCHARGE_DATE  DATE
);

COPY INTO STG_PATIENT_JOURNEY
FROM @STG_PROJECT_19B/raw_patient_journey.csv
FILE_FORMAT = (FORMAT_NAME = FF_CSV_STANDARD)
ON_ERROR = 'ABORT_STATEMENT';

CREATE OR REPLACE TABLE FACT_PATIENT_ADMISSION_LIFECYCLE (
    ENCOUNTER_ID            VARCHAR(20),
    PATIENT_ID              VARCHAR(20),
    TRIAGE_DATE             DATE,
    ADMISSION_DATE          DATE,
    DISCHARGE_DATE          DATE,
    TRIAGE_TO_ADMIT_DAYS    NUMBER,
    LENGTH_OF_STAY_DAYS     NUMBER
);

INSERT INTO FACT_PATIENT_ADMISSION_LIFECYCLE
SELECT
    ENCOUNTER_ID,
    PATIENT_ID,
    TRIAGE_DATE,
    ADMISSION_DATE,
    DISCHARGE_DATE,
    DATEDIFF('day', TRIAGE_DATE, ADMISSION_DATE)    AS TRIAGE_TO_ADMIT_DAYS,
    DATEDIFF('day', ADMISSION_DATE, DISCHARGE_DATE) AS LENGTH_OF_STAY_DAYS
FROM STG_PATIENT_JOURNEY;

SELECT ENCOUNTER_ID, PATIENT_ID, TRIAGE_TO_ADMIT_DAYS, LENGTH_OF_STAY_DAYS
FROM FACT_PATIENT_ADMISSION_LIFECYCLE
ORDER BY ENCOUNTER_ID;

-- TASK 4: Categorize Additive vs Non-Additive Billing Measures
CREATE OR REPLACE TABLE STG_TREATMENT_BILLS (
    CLAIM_ID                VARCHAR(20),
    ENCOUNTER_ID            VARCHAR(20),
    PATIENT_ID              VARCHAR(20),
    PROCEDURE_COST          NUMBER(10,2),
    INSURANCE_DISCOUNT_PCT  NUMBER(5,4),
    COPAY_AMOUNT            NUMBER(10,2)
);

COPY INTO STG_TREATMENT_BILLS
FROM @STG_PROJECT_19B/raw_treatment_bills.csv
FILE_FORMAT = (FORMAT_NAME = FF_CSV_STANDARD)
ON_ERROR = 'ABORT_STATEMENT';

CREATE OR REPLACE TABLE FACT_TREATMENT_BILLING (
    CLAIM_ID                VARCHAR(20),   
    ENCOUNTER_ID             VARCHAR(20),
    PATIENT_ID                VARCHAR(20),
    PROCEDURE_COST             NUMBER(10,2),   
    INSURANCE_DISCOUNT_PCT     NUMBER(5,4),    
    COPAY_AMOUNT                NUMBER(10,2),
    NET_CHARGE                   NUMBER(10,2)   
);

INSERT INTO FACT_TREATMENT_BILLING
SELECT
    CLAIM_ID,
    ENCOUNTER_ID,
    PATIENT_ID,
    PROCEDURE_COST,
    INSURANCE_DISCOUNT_PCT,
    COPAY_AMOUNT,
    (PROCEDURE_COST * (1 - INSURANCE_DISCOUNT_PCT)) - COPAY_AMOUNT AS NET_CHARGE
FROM STG_TREATMENT_BILLS;

SELECT CLAIM_ID, ENCOUNTER_ID, PROCEDURE_COST, COPAY_AMOUNT, NET_CHARGE
FROM FACT_TREATMENT_BILLING
ORDER BY CLAIM_ID;

-- TASK 5: Patient Billing Aggregation
SELECT
    ENCOUNTER_ID,
    SUM(NET_CHARGE)     AS TOTAL_NET_CHARGES,
    AVG(PROCEDURE_COST) AS AVG_PROCEDURE_COST
FROM FACT_TREATMENT_BILLING
GROUP BY ENCOUNTER_ID
ORDER BY ENCOUNTER_ID;

-- TASK 6: Audit Untreated / Non-Billed Encounters
SELECT
    l.ENCOUNTER_ID,
    l.PATIENT_ID,
    'NO_CLAIMS_ISSUED' AS UNBILLED_STATUS
FROM FACT_PATIENT_ADMISSION_LIFECYCLE l
LEFT JOIN FACT_TREATMENT_BILLING b
    ON l.ENCOUNTER_ID = b.ENCOUNTER_ID
WHERE b.ENCOUNTER_ID IS NULL
ORDER BY l.ENCOUNTER_ID;

