-- TASK 1 — Create Database and Schema
CREATE WAREHOUSE P10_WH;
USE WAREHOUSE P10_WH;

CREATE DATABASE P10_DB;

CREATE SCHEMA P10_DB.P10_SCHEMA;

USE DATABASE P10_DB;
USE SCHEMA P10_SCHEMA;

CREATE FILE FORMAT CSV_FILE 
  TYPE = 'CSV'
  FIELD_DELIMITER = ','
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"';

CREATE STAGE P10_STAGE FILE_FORMAT = P10_SCHEMA.CSV_FILE;

-- TASK 2 — Create Type 3 Dimension
CREATE TABLE dim_customer_type3 (
    CUSTOMER_KEY           INT  AUTOINCREMENT PRIMARY KEY,
    CUSTOMER_ID            INT,
    CUSTOMER_NAME          VARCHAR(50),
    CITY                   VARCHAR(50),
    STATE                  VARCHAR(50),
    CURRENT_MEMBERSHIP     VARCHAR(50),
    PREVIOUS_MEMBERSHIP    VARCHAR(50),
    SEGMENT                VARCHAR(50)
);

-- TASK 3 — Load Initial Type 3 Data
COPY INTO dim_customer_type3 (CUSTOMER_ID,CUSTOMER_NAME,CITY,STATE,CURRENT_MEMBERSHIP,PREVIOUS_MEMBERSHIP,SEGMENT)
FROM(
    SELECT $1, $2, $3, $4, $5, NULL, $6
    FROM @P10_STAGE/customers_initial.csv
);

-- TASK 4 — Display Initial Type 3 Data
SELECT 
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP
FROM DIM_CUSTOMER_TYPE3;

-- TASK 5 — Apply SCD Type 3 Changes
CREATE TABLE UPDATED_CUSTOMERS(
    CUSTOMER_ID       INT,
    CUSTOMER_NAME     VARCHAR(50),
    CITY              VARCHAR(50),
    STATE             VARCHAR(50),
    MEMBERSHIP        VARCHAR(50),
    SEGMENT           VARCHAR(50),
    EFFECTIVE_DATE    TIMESTAMP_NTZ
);

COPY INTO UPDATED_CUSTOMERS
FROM @P10_STAGE/customer_updates.csv;

-- TASK 6 — Update Type 3 Dimension
UPDATE DIM_CUSTOMER_TYPE3 AS tgt
SET
    tgt.PREVIOUS_MEMBERSHIP = tgt.CURRENT_MEMBERSHIP,
    tgt.CURRENT_MEMBERSHIP = src.MEMBERSHIP,
    tgt.CITY = src.CITY,
    tgt.STATE = src.STATE
FROM UPDATED_CUSTOMERS AS src
WHERE src.customer_id = tgt.customer_id;

-- TASK 7 — Type 3 Final Report
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP
FROM DIM_CUSTOMER_TYPE3
ORDER BY CUSTOMER_ID;

-- TASK 8 — Demonstrate Type 3
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP
FROM DIM_CUSTOMER_TYPE3
WHERE CUSTOMER_ID = 101;

-- TASK 9 — Create Type 6 Dimension
CREATE TABLE DIM_CUSTOMER_TYPE6(
    CUSTOMER_KEY INT AUTOINCREMENT PRIMARY KEY,
    CUSTOMER_ID INT,
    CUSTOMER_NAME VARCHAR(50),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    CURRENT_MEMBERSHIP VARCHAR(50),
    PREVIOUS_MEMBERSHIP VARCHAR(50),
    HISTORICAL_MEMBERSHIP VARCHAR(50),
    SEGMENT VARCHAR(50),
    EFFECTIVE_DATE TIMESTAMP_NTZ,
    EXPIRY_DATE TIMESTAMP_NTZ,
    IS_CURRENT BOOLEAN
);

-- TASK 10 — Load Initial Type 6 Records
COPY INTO DIM_CUSTOMER_TYPE6(CUSTOMER_ID, CUSTOMER_NAME, CITY, STATE, CURRENT_MEMBERSHIP, PREVIOUS_MEMBERSHIP, HISTORICAL_MEMBERSHIP, SEGMENT, EFFECTIVE_DATE, EXPIRY_DATE, IS_CURRENT)
FROM(
    SELECT $1,$2,$3,$4,$5,NULL,$5,$6,'2026-01-01', '9999-12-31', TRUE
    FROM @P10_STAGE/customers_initial.csv
);

-- TASK 11 — Apply Type 6 Change for Customer 101

UPDATE DIM_CUSTOMER_TYPE6
SET
    EXPIRY_DATE = '2026-03-31',
    IS_CURRENT = FALSE
WHERE CUSTOMER_ID = 101 AND IS_CURRENT = TRUE;

INSERT INTO DIM_CUSTOMER_TYPE6 (CUSTOMER_ID, CUSTOMER_NAME, CITY, STATE, CURRENT_MEMBERSHIP, PREVIOUS_MEMBERSHIP, HISTORICAL_MEMBERSHIP, SEGMENT, EFFECTIVE_DATE, EXPIRY_DATE, IS_CURRENT)
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,        
    'Silver',        
    MEMBERSHIP,        
    SEGMENT,
    '2026-04-01',
    '9999-12-31',
    TRUE
FROM UPDATED_CUSTOMERS
WHERE CUSTOMER_ID = 101;

-- TASK 12 — Apply Remaining Changes
UPDATE DIM_CUSTOMER_TYPE6
SET
    EXPIRY_DATE = '2026-04-04',
    IS_CURRENT = FALSE
WHERE CUSTOMER_ID = 103 AND IS_CURRENT = TRUE;

INSERT INTO DIM_CUSTOMER_TYPE6 (CUSTOMER_ID, CUSTOMER_NAME, CITY, STATE, CURRENT_MEMBERSHIP, PREVIOUS_MEMBERSHIP, HISTORICAL_MEMBERSHIP, SEGMENT, EFFECTIVE_DATE, EXPIRY_DATE, IS_CURRENT)
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,        
    'Silver',        
    MEMBERSHIP,        
    SEGMENT,
    '2026-04-05',
    '9999-12-31',
    TRUE
FROM UPDATED_CUSTOMERS
WHERE CUSTOMER_ID = 103;

UPDATE DIM_CUSTOMER_TYPE6
SET
    EXPIRY_DATE = '2026-04-09',
    IS_CURRENT = FALSE
WHERE CUSTOMER_ID = 104 AND IS_CURRENT = TRUE;

INSERT INTO DIM_CUSTOMER_TYPE6 (CUSTOMER_ID, CUSTOMER_NAME, CITY, STATE, CURRENT_MEMBERSHIP, PREVIOUS_MEMBERSHIP, HISTORICAL_MEMBERSHIP, SEGMENT, EFFECTIVE_DATE, EXPIRY_DATE, IS_CURRENT)
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,        
    'Gold',        
    MEMBERSHIP,        
    SEGMENT,
    '2026-04-10',
    '9999-12-31',
    TRUE
FROM UPDATED_CUSTOMERS
WHERE CUSTOMER_ID = 104;

-- TASK 13 — Display Complete Type 6 History
SELECT CUSTOMER_ID, CUSTOMER_NAME, CURRENT_MEMBERSHIP, PREVIOUS_MEMBERSHIP, EFFECTIVE_DATE, EXPIRY_DATE, IS_CURRENT
FROM DIM_CUSTOMER_TYPE6
ORDER BY CUSTOMER_ID, EFFECTIVE_DATE;

-- TASK 14 — Current Customer Report
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP
FROM DIM_CUSTOMER_TYPE6
WHERE IS_CURRENT = TRUE
ORDER BY CUSTOMER_ID;

-- TASK 15 — Point-in-Time Historical Query
SELECT CUSTOMER_ID, CUSTOMER_NAME, CURRENT_MEMBERSHIP, EFFECTIVE_DATE, EXPIRY_DATE
FROM DIM_CUSTOMER_TYPE6
WHERE CUSTOMER_ID = 101
  AND '2026-03-15' BETWEEN EFFECTIVE_DATE AND EXPIRY_DATE;