CREATE WAREHOUSE IF NOT EXISTS P19C_WH;
USE WAREHOUSE P19C_WH;

CREATE DATABASE IF NOT EXISTS P19C_DB;
USE DATABASE P19C_DB;

CREATE SCHEMA IF NOT EXISTS PROJECT_19C;
USE SCHEMA PROJECT_19C;

CREATE OR REPLACE FILE FORMAT FF_CSV_STANDARD
    TYPE = 'CSV'
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    NULL_IF = ('NULL', '')
    EMPTY_FIELD_AS_NULL = TRUE;

CREATE OR REPLACE STAGE STG_PROJECT_19C
    FILE_FORMAT = FF_CSV_STANDARD;

CREATE OR REPLACE TABLE STG_WIRE_TRANSFERS (
    TXN_ID          VARCHAR(20),
    TXN_DATE        DATE,
    SENDER_ACC      VARCHAR(20),
    RECEIVER_ACC    VARCHAR(20),
    AMOUNT          NUMBER(15,2),
    FEE             NUMBER(10,2),
    CURRENCY_RATE   NUMBER(10,4),
    AUTH_METHOD     VARCHAR(20),
    RISK_FLAG       VARCHAR(10),
    TRANSFER_TYPE   VARCHAR(20)
);


COPY INTO STG_WIRE_TRANSFERS
FROM @STG_PROJECT_19C/raw_wire_transfers.csv
FILE_FORMAT = (FORMAT_NAME = FF_CSV_STANDARD)
ON_ERROR = 'ABORT_STATEMENT';

CREATE OR REPLACE TABLE STG_VAULT_CASH (
    SNAPSHOT_DATE       DATE,
    VAULT_ID            VARCHAR(20),
    CURRENCY_CODE       VARCHAR(5),
    OPENING_BALANCE     NUMBER(15,2),
    CLOSING_BALANCE     NUMBER(15,2),
    RESERVE_RATIO_PCT   NUMBER(6,4)
);

COPY INTO STG_VAULT_CASH
FROM @STG_PROJECT_19C/raw_vault_cash.csv
FILE_FORMAT = (FORMAT_NAME = FF_CSV_STANDARD)
ON_ERROR = 'ABORT_STATEMENT';

CREATE OR REPLACE TABLE STG_CREDIT_LIFECYCLES (
    APP_ID                VARCHAR(20),
    SUBMISSION_DATE       DATE,
    UNDERWRITE_DATE       DATE,
    RISK_APPROVAL_DATE    DATE,
    DISBURSEMENT_DATE     DATE
);

COPY INTO STG_CREDIT_LIFECYCLES
FROM @STG_PROJECT_19C/raw_credit_lifecycles.csv
FILE_FORMAT = (FORMAT_NAME = FF_CSV_STANDARD)
ON_ERROR = 'ABORT_STATEMENT';

CREATE OR REPLACE TABLE STG_AUDIT_COVERAGE (
    AUDIT_YEAR          NUMBER(4,0),
    QUARTER             VARCHAR(5),
    ACCOUNT_ID          VARCHAR(20),
    AUDITOR_FIRM        VARCHAR(50),
    COMPLIANCE_STATUS   VARCHAR(20)
);

COPY INTO STG_AUDIT_COVERAGE
FROM @STG_PROJECT_19C/raw_audit_coverage.csv
FILE_FORMAT = (FORMAT_NAME = FF_CSV_STANDARD)
ON_ERROR = 'ABORT_STATEMENT';

-- TASK 1: Advanced Junk Dimension Construction
CREATE OR REPLACE TABLE DIM_WIRE_ATTRIBUTES (
    ATTRIBUTE_SK    NUMBER(10,0),
    AUTH_METHOD     VARCHAR(20),
    RISK_FLAG       VARCHAR(10),
    TRANSFER_TYPE   VARCHAR(20)
);

INSERT INTO DIM_WIRE_ATTRIBUTES
SELECT
    ROW_NUMBER() OVER (ORDER BY MIN(TXN_ID)) AS ATTRIBUTE_SK,
    AUTH_METHOD,
    RISK_FLAG,
    TRANSFER_TYPE
FROM STG_WIRE_TRANSFERS
GROUP BY AUTH_METHOD, RISK_FLAG, TRANSFER_TYPE;

SELECT * FROM DIM_WIRE_ATTRIBUTES ORDER BY ATTRIBUTE_SK;

-- TASK 2: Wire Transfer Fact Table & Currency Normalized Measures
CREATE OR REPLACE TABLE FACT_WIRE_TRANSFERS (
    TXN_ID             VARCHAR(20),
    TXN_DATE           DATE,
    SENDER_ACC         VARCHAR(20),
    RECEIVER_ACC       VARCHAR(20),
    ATTRIBUTE_SK       NUMBER(10,0),
    AMOUNT             NUMBER(15,2),
    FEE                NUMBER(10,2),
    CURRENCY_RATE      NUMBER(10,4),
    BASE_VAL_USD       NUMBER(15,2),
    NET_TRANSFER_VAL   NUMBER(15,2)
);

INSERT INTO FACT_WIRE_TRANSFERS
SELECT
    w.TXN_ID,
    w.TXN_DATE,
    w.SENDER_ACC,
    w.RECEIVER_ACC,
    d.ATTRIBUTE_SK,
    w.AMOUNT,
    w.FEE,
    w.CURRENCY_RATE,
    w.AMOUNT * w.CURRENCY_RATE AS BASE_VAL_USD,
    (w.AMOUNT * w.CURRENCY_RATE) - w.FEE AS NET_TRANSFER_VAL
FROM STG_WIRE_TRANSFERS w
JOIN DIM_WIRE_ATTRIBUTES d
    ON w.AUTH_METHOD = d.AUTH_METHOD
   AND w.RISK_FLAG = d.RISK_FLAG
   AND w.TRANSFER_TYPE = d.TRANSFER_TYPE;

SELECT TXN_ID, SENDER_ACC, ATTRIBUTE_SK, AMOUNT, BASE_VAL_USD, NET_TRANSFER_VAL
FROM FACT_WIRE_TRANSFERS
ORDER BY TXN_ID;

-- TASK 3: Periodic Vault Snapshot & Non-Additive Reserve Validation
CREATE OR REPLACE TABLE FACT_VAULT_CASH_SNAPSHOT (
    SNAPSHOT_DATE       DATE,
    VAULT_ID            VARCHAR(20),
    CURRENCY_CODE       VARCHAR(5),
    OPENING_BALANCE     NUMBER(15,2),
    CLOSING_BALANCE     NUMBER(15,2),
    RESERVE_RATIO_PCT   NUMBER(6,4),
    NET_DAILY_CHANGE    NUMBER(15,2)
);

INSERT INTO FACT_VAULT_CASH_SNAPSHOT
SELECT
    SNAPSHOT_DATE,
    VAULT_ID,
    CURRENCY_CODE,
    OPENING_BALANCE,
    CLOSING_BALANCE,
    RESERVE_RATIO_PCT,
    CLOSING_BALANCE - OPENING_BALANCE AS NET_DAILY_CHANGE
FROM STG_VAULT_CASH;

SELECT
    SNAPSHOT_DATE,
    SUM(OPENING_BALANCE) AS TOTAL_OPENING_USD_EQU,
    SUM(CLOSING_BALANCE) AS TOTAL_CLOSING_USD_EQU
FROM FACT_VAULT_CASH_SNAPSHOT
GROUP BY SNAPSHOT_DATE
ORDER BY SNAPSHOT_DATE;

-- TASK 4: Loan Application Accumulating Milestone Duration Table
CREATE OR REPLACE TABLE FACT_CREDIT_APPROVAL_LIFECYCLE (
    APP_ID                VARCHAR(20),
    SUBMISSION_DATE       DATE,
    UNDERWRITE_DATE       DATE,
    RISK_APPROVAL_DATE    DATE,
    DISBURSEMENT_DATE     DATE,
    UNDERWRITE_DAYS       NUMBER(5,0),
    RISK_APPROVAL_DAYS    NUMBER(5,0),
    DISBURSEMENT_DAYS     NUMBER(5,0),
    TOTAL_CYCLE_DAYS      NUMBER(5,0)
);

INSERT INTO FACT_CREDIT_APPROVAL_LIFECYCLE
SELECT
    APP_ID,
    SUBMISSION_DATE,
    UNDERWRITE_DATE,
    RISK_APPROVAL_DATE,
    DISBURSEMENT_DATE,
    DATEDIFF('day', SUBMISSION_DATE, UNDERWRITE_DATE)      AS UNDERWRITE_DAYS,
    DATEDIFF('day', UNDERWRITE_DATE, RISK_APPROVAL_DATE)   AS RISK_APPROVAL_DAYS,
    DATEDIFF('day', RISK_APPROVAL_DATE, DISBURSEMENT_DATE) AS DISBURSEMENT_DAYS,
    DATEDIFF('day', SUBMISSION_DATE, DISBURSEMENT_DATE)    AS TOTAL_CYCLE_DAYS
FROM STG_CREDIT_LIFECYCLES;

SELECT APP_ID, UNDERWRITE_DAYS, RISK_APPROVAL_DAYS, DISBURSEMENT_DAYS, TOTAL_CYCLE_DAYS
FROM FACT_CREDIT_APPROVAL_LIFECYCLE
ORDER BY APP_ID;

-- TASK 5: Bottleneck Stage Identification in Credit Pipeline
SELECT
    APP_ID,
    SUBMISSION_DATE,
    CASE
        WHEN UNDERWRITE_DATE IS NULL THEN 'AWAITING_UNDERWRITE'
        WHEN RISK_APPROVAL_DATE IS NULL THEN 'AWAITING_RISK_AUTH'
        WHEN DISBURSEMENT_DATE IS NULL THEN 'AWAITING_DISBURSAL'
    END AS CURRENT_BOTTLENECK
FROM FACT_CREDIT_APPROVAL_LIFECYCLE
WHERE DISBURSEMENT_DATE IS NULL
ORDER BY APP_ID;

-- TASK 6: Factless Audit Coverage Matrix Analysis
CREATE OR REPLACE TABLE FACTLESS_COMPLIANCE_AUDIT_COVERAGE (
    AUDIT_YEAR          NUMBER(4,0),
    QUARTER             VARCHAR(5),
    ACCOUNT_ID          VARCHAR(20),
    AUDITOR_FIRM        VARCHAR(50),
    COMPLIANCE_STATUS   VARCHAR(20)
);

INSERT INTO FACTLESS_COMPLIANCE_AUDIT_COVERAGE
SELECT AUDIT_YEAR, QUARTER, ACCOUNT_ID, AUDITOR_FIRM, COMPLIANCE_STATUS
FROM STG_AUDIT_COVERAGE;

WITH HIGH_RISK_ACCOUNTS AS (
    SELECT
        f.SENDER_ACC AS ACCOUNT_ID,
        COUNT(*) AS HIGH_RISK_TXN_COUNT
    FROM FACT_WIRE_TRANSFERS f
    JOIN DIM_WIRE_ATTRIBUTES d ON f.ATTRIBUTE_SK = d.ATTRIBUTE_SK
    WHERE d.RISK_FLAG = 'HIGH'
    GROUP BY f.SENDER_ACC
),
AUDITED_2026 AS (
    SELECT DISTINCT ACCOUNT_ID
    FROM FACTLESS_COMPLIANCE_AUDIT_COVERAGE
    WHERE AUDIT_YEAR = 2026
)
SELECT
    h.ACCOUNT_ID,
    h.HIGH_RISK_TXN_COUNT,
    CASE WHEN a.ACCOUNT_ID IS NOT NULL THEN 'AUDITED' ELSE 'NOT_AUDITED' END AS COMPLIANCE_STATUS
FROM HIGH_RISK_ACCOUNTS h
LEFT JOIN AUDITED_2026 a ON h.ACCOUNT_ID = a.ACCOUNT_ID
ORDER BY h.ACCOUNT_ID;

-- TASK 7: Risk Profile Revenue Cross-Analysis
SELECT
    d.RISK_FLAG,
    d.TRANSFER_TYPE,
    COUNT(*) AS TOTAL_TXNS,
    SUM(f.FEE) AS TOTAL_FEES,
    SUM(f.BASE_VAL_USD) AS TOTAL_VOLUME_USD
FROM FACT_WIRE_TRANSFERS f
JOIN DIM_WIRE_ATTRIBUTES d ON f.ATTRIBUTE_SK = d.ATTRIBUTE_SK
GROUP BY d.RISK_FLAG, d.TRANSFER_TYPE
ORDER BY d.RISK_FLAG, d.TRANSFER_TYPE;

-- TASK 8: Multi-Fact Comprehensive Reconciliation Audit
WITH WIRE_TOTAL AS (
    SELECT SUM(BASE_VAL_USD) AS TOTAL_WIRE_VOL_USD
    FROM FACT_WIRE_TRANSFERS
),
VAULT_LATEST AS (
    SELECT SUM(CLOSING_BALANCE) AS VAULT_CLOSING_USD
    FROM FACT_VAULT_CASH_SNAPSHOT
    WHERE SNAPSHOT_DATE = (SELECT MAX(SNAPSHOT_DATE) FROM FACT_VAULT_CASH_SNAPSHOT)
),
LOAN_COMPLETE AS (
    SELECT COUNT(*) AS COMPLETED_LOAN_APPS
    FROM FACT_CREDIT_APPROVAL_LIFECYCLE
    WHERE DISBURSEMENT_DATE IS NOT NULL
)
SELECT
    w.TOTAL_WIRE_VOL_USD,
    v.VAULT_CLOSING_USD,
    l.COMPLETED_LOAN_APPS,
    CASE
        WHEN w.TOTAL_WIRE_VOL_USD > 0
         AND v.VAULT_CLOSING_USD > 0
         AND l.COMPLETED_LOAN_APPS >= 0
        THEN TRUE ELSE FALSE
    END AS AUDIT_SANITY_FLAG
FROM WIRE_TOTAL w, VAULT_LATEST v, LOAN_COMPLETE l;