-- TASK 1 — Create Database and Schema
CREATE WAREHOUSE P11_WH;
USE WAREHOUSE P11_WH;

CREATE DATABASE P11_DB;
USE DATABASE P11_DB;

CREATE SCHEMA P11_SCHEMA;
USE SCHEMA P11_SCHEMA;

CREATE OR REPLACE FILE FORMAT CSV_FILE
    TYPE = 'CSV'
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"';
    
CREATE STAGE P11_STAGE FILE_FORMAT = CSV_FILE;

-- TASK 2 — Create Hybrid Dimension Table
CREATE TABLE HYBRID_TABLE(
    CUSTOMER_KEY INT AUTOINCREMENT PRIMARY KEY,
    CUSTOMER_ID INT,
    CUSTOMER_NAME VARCHAR(50),
    CITY VARCHAR(50),
    PREVIOUS_CITY VARCHAR(50),
    STATE VARCHAR(50),
    CURRENT_MEMBERSHIP VARCHAR(50),
    PREVIOUS_MEMBERSHIP VARCHAR(50),
    HISTORICAL_MEMBERSHIP VARCHAR(50),
    SEGMENT VARCHAR(50),
    EFFECTIVE_DATE DATE,
    EXPIRY_DATE DATE,
    IS_CURRENT BOOLEAN
);

-- TASK 3 — Load Initial Dimension Data
COPY INTO HYBRID_TABLE (CUSTOMER_ID, CUSTOMER_NAME, CITY, PREVIOUS_CITY, STATE, CURRENT_MEMBERSHIP, PREVIOUS_MEMBERSHIP, HISTORICAL_MEMBERSHIP, SEGMENT, EFFECTIVE_DATE, EXPIRY_DATE, IS_CURRENT)
FROM(
    SELECT $1,$2,$3,NULL,$4,$5,NULL,$5,$6,'2026-01-01', '9999-12-31', TRUE
    FROM @P11_STAGE/customers_initial.csv
);

-- TASK 4 — Display Initial Dimension State
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    PREVIOUS_CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM HYBRID_TABLE;

-- TASK 5 — Apply Hybrid Updates for Customers 101, 103, and 104
CREATE TABLE STG_CUSTOMER_UPDATES (
    CUSTOMER_ID INT, CUSTOMER_NAME VARCHAR(50), CITY VARCHAR(50),
    STATE VARCHAR(50), MEMBERSHIP VARCHAR(50), SEGMENT VARCHAR(50), EFFECTIVE_DATE DATE
);

COPY INTO STG_CUSTOMER_UPDATES
FROM @P11_STAGE/customer_updates.csv;

UPDATE HYBRID_TABLE SET EXPIRY_DATE = '2026-03-31', IS_CURRENT = FALSE WHERE CUSTOMER_ID = 101 AND IS_CURRENT = TRUE;
UPDATE HYBRID_TABLE SET EXPIRY_DATE = '2026-04-04', IS_CURRENT = FALSE WHERE CUSTOMER_ID = 103 AND IS_CURRENT = TRUE;
UPDATE HYBRID_TABLE SET EXPIRY_DATE = '2026-04-09', IS_CURRENT = FALSE WHERE CUSTOMER_ID = 104 AND IS_CURRENT = TRUE;

INSERT INTO HYBRID_TABLE (CUSTOMER_ID, CUSTOMER_NAME, CITY, PREVIOUS_CITY, STATE,
                           CURRENT_MEMBERSHIP, PREVIOUS_MEMBERSHIP, HISTORICAL_MEMBERSHIP,
                           SEGMENT, EFFECTIVE_DATE, EXPIRY_DATE, IS_CURRENT)
SELECT u.CUSTOMER_ID, u.CUSTOMER_NAME,
       u.CITY,
       CASE WHEN u.CITY <> h.CITY THEN h.CITY ELSE NULL END,
       u.STATE,
       u.MEMBERSHIP,
       h.CURRENT_MEMBERSHIP,
       u.MEMBERSHIP,
       u.SEGMENT,
       u.EFFECTIVE_DATE, '9999-12-31', TRUE
FROM STG_CUSTOMER_UPDATES u
JOIN HYBRID_TABLE h ON h.CUSTOMER_ID = u.CUSTOMER_ID AND h.IS_CURRENT = FALSE;

UPDATE HYBRID_TABLE SET CITY='Bengaluru', PREVIOUS_CITY='Hyderabad', STATE='Karnataka', CURRENT_MEMBERSHIP='Gold', PREVIOUS_MEMBERSHIP='Silver' WHERE CUSTOMER_ID=101;
UPDATE HYBRID_TABLE SET CITY='Chennai', PREVIOUS_CITY='Vijayawada', STATE='Tamil Nadu', CURRENT_MEMBERSHIP='Gold', PREVIOUS_MEMBERSHIP='Silver' WHERE CUSTOMER_ID=103;
UPDATE HYBRID_TABLE SET CITY='Hyderabad', PREVIOUS_CITY=NULL, STATE='Telangana', CURRENT_MEMBERSHIP='Platinum', PREVIOUS_MEMBERSHIP='Gold' WHERE CUSTOMER_ID=104;

SELECT 'Hybrid SCD Updates Applied Successfully.' AS STATUS;
SELECT 'Total Records = ' || COUNT(*) AS STATUS FROM HYBRID_TABLE;
SELECT 'Current Records = ' || COUNT(*) AS STATUS FROM HYBRID_TABLE WHERE IS_CURRENT = TRUE;
SELECT 'Historical Records = ' || COUNT(*) AS STATUS FROM HYBRID_TABLE WHERE IS_CURRENT = FALSE;

-- TASK 6 — Display Complete Dimension History
SELECT CUSTOMER_ID, CUSTOMER_NAME, CITY, PREVIOUS_CITY, STATE,
       CURRENT_MEMBERSHIP, PREVIOUS_MEMBERSHIP, HISTORICAL_MEMBERSHIP,
       SEGMENT, EFFECTIVE_DATE, EXPIRY_DATE, IS_CURRENT
FROM HYBRID_TABLE
ORDER BY CUSTOMER_ID, EFFECTIVE_DATE;

-- TASK 7 — Display Active Customer Report
SELECT CUSTOMER_ID, CUSTOMER_NAME, CITY, PREVIOUS_CITY, STATE,
       CURRENT_MEMBERSHIP, PREVIOUS_MEMBERSHIP, SEGMENT
FROM HYBRID_TABLE
WHERE IS_CURRENT = TRUE
ORDER BY CUSTOMER_ID;

    -- TASK 8 — Point-in-Time Historical Query
SELECT CUSTOMER_ID, CUSTOMER_NAME, CITY, HISTORICAL_MEMBERSHIP, SEGMENT,
       EFFECTIVE_DATE, EXPIRY_DATE
FROM HYBRID_TABLE
WHERE CUSTOMER_ID = 101
  AND EFFECTIVE_DATE <= '2026-03-15'
  AND EXPIRY_DATE >= '2026-03-15';
