-- TASK 1 — Create Environment Context
CREATE WAREHOUSE P13b_WH;
USE WAREHOUSE P13b_WH;

CREATE DATABASE HEALTHCARE_DW;
CREATE SCHEMA HEALTHCARE_DW.SCHEMA_COMPARE_LAB;

USE DATABASE HEALTHCARE_DW;
USE SCHEMA SCHEMA_COMPARE_LAB;

-- TASK 2 — Build Star Schema Denormalized Hospital Dimension (`STAR_DIM_HOSPITAL`)
CREATE TABLE STAR_DIM_HOSPITAL (
    HOSPITAL_KEY     NUMBER AUTOINCREMENT PRIMARY KEY,
    HOSPITAL_ID      NUMBER,
    HOSPITAL_NAME    VARCHAR(100),
    CITY             VARCHAR(50),
    STATE            VARCHAR(50),
    NETWORK_NAME     VARCHAR(100),
    NETWORK_DIRECTOR VARCHAR(100)
);

-- TASK 3 — Build Star Schema Denormalized Treatment Dimension (`STAR_DIM_TREATMENT`)
CREATE TABLE STAR_DIM_TREATMENT (
    TREATMENT_KEY        NUMBER AUTOINCREMENT PRIMARY KEY,
    TREATMENT_ID         NUMBER,
    TREATMENT_NAME       VARCHAR(100),
    DIAGNOSIS_GROUP_NAME VARCHAR(50),
    STANDARD_COST        NUMBER(12,2)
);

-- TASK 4 — Load Star Schema Dimension Data
CREATE FILE FORMAT CSV_FORMAT
    TYPE = 'CSV'
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    SKIP_HEADER = 1;

CREATE STAGE P13B_STAGE FILE_FORMAT = CSV_FORMAT;

COPY INTO STAR_DIM_HOSPITAL (HOSPITAL_ID, HOSPITAL_NAME, CITY, STATE, NETWORK_NAME, NETWORK_DIRECTOR)
FROM (
    SELECT $1, $2, $3, $4, $6, $7
    FROM @P13B_STAGE/hospital_hierarchy.csv
);

COPY INTO STAR_DIM_TREATMENT (TREATMENT_ID, TREATMENT_NAME, DIAGNOSIS_GROUP_NAME, STANDARD_COST)
FROM (
    SELECT $1, $2, $4, $5
    FROM @P13B_STAGE/treatment_hierarchy.csv
);

SELECT COUNT(*) AS ROWS_LOADED FROM STAR_DIM_HOSPITAL;   
SELECT COUNT(*) AS ROWS_LOADED FROM STAR_DIM_TREATMENT;  

-- TASK 5 — Build & Load Star Schema Claims Fact Table (STAR_FACT_CLAIMS)
CREATE TABLE STAR_FACT_CLAIMS (
    CLAIM_KEY        NUMBER AUTOINCREMENT PRIMARY KEY,
    CLAIM_ID         VARCHAR(50),
    CLAIM_DATE       DATE,
    PATIENT_ID       NUMBER,
    HOSPITAL_KEY     NUMBER,
    TREATMENT_KEY    NUMBER,
    CLAIMED_AMOUNT   NUMBER(12,2),
    APPROVED_AMOUNT  NUMBER(12,2)
);

CREATE TABLE STG_INSURANCE_CLAIMS (
    CLAIM_ID         VARCHAR(50),
    CLAIM_DATE       DATE,
    PATIENT_ID       NUMBER,
    HOSPITAL_ID      NUMBER,
    TREATMENT_ID     NUMBER,
    CLAIMED_AMOUNT   NUMBER(12,2),
    APPROVED_AMOUNT  NUMBER(12,2)
);

COPY INTO STG_INSURANCE_CLAIMS
FROM @P13B_STAGE/insurance_claims.csv;

INSERT INTO STAR_FACT_CLAIMS (CLAIM_ID, CLAIM_DATE, PATIENT_ID, HOSPITAL_KEY, TREATMENT_KEY, CLAIMED_AMOUNT, APPROVED_AMOUNT)
SELECT c.CLAIM_ID, c.CLAIM_DATE, c.PATIENT_ID, h.HOSPITAL_KEY, t.TREATMENT_KEY, c.CLAIMED_AMOUNT, c.APPROVED_AMOUNT
FROM STG_INSURANCE_CLAIMS c
JOIN STAR_DIM_HOSPITAL h  ON c.HOSPITAL_ID  = h.HOSPITAL_ID
JOIN STAR_DIM_TREATMENT t ON c.TREATMENT_ID = t.TREATMENT_ID;

SELECT COUNT(*) AS ROWS_LOADED FROM STAR_FACT_CLAIMS;  

-- TASK 6 — Build Normalized Snowflake Schema Hospital Hierarchy
CREATE TABLE SNOW_DIM_NETWORK (
    NETWORK_KEY      NUMBER AUTOINCREMENT PRIMARY KEY,
    NETWORK_ID       NUMBER,
    NETWORK_NAME     VARCHAR(100),
    NETWORK_DIRECTOR VARCHAR(100)
);

CREATE TABLE SNOW_DIM_HOSPITAL (
    HOSPITAL_KEY   NUMBER AUTOINCREMENT PRIMARY KEY,
    HOSPITAL_ID    NUMBER,
    HOSPITAL_NAME  VARCHAR(100),
    CITY           VARCHAR(50),
    STATE          VARCHAR(50),
    NETWORK_KEY    NUMBER,
    FOREIGN KEY (NETWORK_KEY) REFERENCES SNOW_DIM_NETWORK(NETWORK_KEY)
);

-- TASK 7 — Build Normalized Snowflake Schema Treatment Hierarchy
CREATE TABLE SNOW_DIM_DIAGNOSIS_GROUP (
    DIAGNOSIS_GROUP_KEY  NUMBER AUTOINCREMENT PRIMARY KEY,
    DIAGNOSIS_GROUP_ID   VARCHAR(20),
    DIAGNOSIS_GROUP_NAME VARCHAR(50)
);

CREATE TABLE SNOW_DIM_TREATMENT (
    TREATMENT_KEY        NUMBER AUTOINCREMENT PRIMARY KEY,
    TREATMENT_ID         NUMBER,
    TREATMENT_NAME       VARCHAR(100),
    STANDARD_COST        NUMBER(12,2),
    DIAGNOSIS_GROUP_KEY  NUMBER,
    FOREIGN KEY (DIAGNOSIS_GROUP_KEY) REFERENCES SNOW_DIM_DIAGNOSIS_GROUP(DIAGNOSIS_GROUP_KEY)
);

-- TASK 8 — Populate Snowflake Schema Normalized Hierarchies
CREATE TABLE STG_HOSPITAL_HIERARCHY (
    HOSPITAL_ID       NUMBER,
    HOSPITAL_NAME     VARCHAR(100),
    CITY              VARCHAR(50),
    STATE             VARCHAR(50),
    NETWORK_ID        NUMBER,
    NETWORK_NAME      VARCHAR(100),
    NETWORK_DIRECTOR  VARCHAR(100)
);
COPY INTO STG_HOSPITAL_HIERARCHY
FROM @P13B_STAGE/hospital_hierarchy.csv;

CREATE TABLE STG_TREATMENT_HIERARCHY (
    TREATMENT_ID          NUMBER,
    TREATMENT_NAME        VARCHAR(100),
    DIAGNOSIS_GROUP_ID    VARCHAR(20),
    DIAGNOSIS_GROUP_NAME  VARCHAR(50),
    STANDARD_COST         NUMBER(12,2)
);
COPY INTO STG_TREATMENT_HIERARCHY
FROM @P13B_STAGE/treatment_hierarchy.csv;

INSERT INTO SNOW_DIM_NETWORK (NETWORK_ID, NETWORK_NAME, NETWORK_DIRECTOR)
SELECT DISTINCT NETWORK_ID, NETWORK_NAME, NETWORK_DIRECTOR
FROM STG_HOSPITAL_HIERARCHY;

INSERT INTO SNOW_DIM_DIAGNOSIS_GROUP (DIAGNOSIS_GROUP_ID, DIAGNOSIS_GROUP_NAME)
SELECT DISTINCT DIAGNOSIS_GROUP_ID, DIAGNOSIS_GROUP_NAME
FROM STG_TREATMENT_HIERARCHY;

INSERT INTO SNOW_DIM_HOSPITAL (HOSPITAL_ID, HOSPITAL_NAME, CITY, STATE, NETWORK_KEY)
SELECT s.HOSPITAL_ID, s.HOSPITAL_NAME, s.CITY, s.STATE, n.NETWORK_KEY
FROM STG_HOSPITAL_HIERARCHY s
JOIN SNOW_DIM_NETWORK n ON s.NETWORK_ID = n.NETWORK_ID;

INSERT INTO SNOW_DIM_TREATMENT (TREATMENT_ID, TREATMENT_NAME, STANDARD_COST, DIAGNOSIS_GROUP_KEY)
SELECT s.TREATMENT_ID, s.TREATMENT_NAME, s.STANDARD_COST, dg.DIAGNOSIS_GROUP_KEY
FROM STG_TREATMENT_HIERARCHY s
JOIN SNOW_DIM_DIAGNOSIS_GROUP dg ON s.DIAGNOSIS_GROUP_ID = dg.DIAGNOSIS_GROUP_ID;

SELECT COUNT(*) FROM SNOW_DIM_NETWORK;
SELECT COUNT(*) FROM SNOW_DIM_HOSPITAL;
SELECT COUNT(*) FROM SNOW_DIM_DIAGNOSIS_GROUP; 
SELECT COUNT(*) FROM SNOW_DIM_TREATMENT;         

-- TASK 9 — Build & Load Snowflake Schema Claims Fact Table (SNOW_FACT_CLAIMS)
CREATE TABLE SNOW_FACT_CLAIMS (
    CLAIM_KEY        NUMBER AUTOINCREMENT PRIMARY KEY,
    CLAIM_ID         VARCHAR(50),
    CLAIM_DATE       DATE,
    PATIENT_ID       NUMBER,
    HOSPITAL_KEY     NUMBER,
    TREATMENT_KEY    NUMBER,
    CLAIMED_AMOUNT   NUMBER(12,2),
    APPROVED_AMOUNT  NUMBER(12,2),
    FOREIGN KEY (HOSPITAL_KEY) REFERENCES SNOW_DIM_HOSPITAL(HOSPITAL_KEY),
    FOREIGN KEY (TREATMENT_KEY) REFERENCES SNOW_DIM_TREATMENT(TREATMENT_KEY)
);

INSERT INTO SNOW_FACT_CLAIMS (CLAIM_ID, CLAIM_DATE, PATIENT_ID, HOSPITAL_KEY, TREATMENT_KEY, CLAIMED_AMOUNT, APPROVED_AMOUNT)
SELECT c.CLAIM_ID, c.CLAIM_DATE, c.PATIENT_ID, h.HOSPITAL_KEY, t.TREATMENT_KEY, c.CLAIMED_AMOUNT, c.APPROVED_AMOUNT
FROM STG_INSURANCE_CLAIMS c
JOIN SNOW_DIM_HOSPITAL h  ON c.HOSPITAL_ID  = h.HOSPITAL_ID
JOIN SNOW_DIM_TREATMENT t ON c.TREATMENT_ID = t.TREATMENT_ID;

-- TASK 10 — Star Schema Specialty Claims Analysis (Flat 1-Hop Query)
SELECT
    t.DIAGNOSIS_GROUP_NAME,
    SUM(f.CLAIMED_AMOUNT)  AS TOTAL_CLAIMED_AMOUNT,
    SUM(f.APPROVED_AMOUNT) AS TOTAL_APPROVED_AMOUNT
FROM STAR_FACT_CLAIMS f
JOIN STAR_DIM_TREATMENT t ON f.TREATMENT_KEY = t.TREATMENT_KEY
GROUP BY t.DIAGNOSIS_GROUP_NAME
ORDER BY t.DIAGNOSIS_GROUP_NAME;

-- TASK 11 — Snowflake Schema Specialty Claims Analysis (Multi-Hop Join Query)
SELECT
    dg.DIAGNOSIS_GROUP_NAME,
    SUM(f.CLAIMED_AMOUNT)  AS TOTAL_CLAIMED_AMOUNT,
    SUM(f.APPROVED_AMOUNT) AS TOTAL_APPROVED_AMOUNT
FROM SNOW_FACT_CLAIMS f
JOIN SNOW_DIM_TREATMENT t ON f.TREATMENT_KEY = t.TREATMENT_KEY
JOIN SNOW_DIM_DIAGNOSIS_GROUP dg ON t.DIAGNOSIS_GROUP_KEY = dg.DIAGNOSIS_GROUP_KEY
GROUP BY dg.DIAGNOSIS_GROUP_NAME
ORDER BY dg.DIAGNOSIS_GROUP_NAME;

-- TASK 12 — Hospital Network Director Performance Report
-- Star Schema
SELECT
    h.NETWORK_DIRECTOR,
    COUNT(f.CLAIM_KEY)     AS TOTAL_CLAIMS_HANDLED,
    SUM(f.APPROVED_AMOUNT) AS TOTAL_APPROVED_AMOUNT
FROM STAR_FACT_CLAIMS f
JOIN STAR_DIM_HOSPITAL h ON f.HOSPITAL_KEY = h.HOSPITAL_KEY
GROUP BY h.NETWORK_DIRECTOR
ORDER BY TOTAL_CLAIMS_HANDLED DESC;

-- Snowflake Schema
SELECT
    n.NETWORK_DIRECTOR,
    COUNT(f.CLAIM_KEY)     AS TOTAL_CLAIMS_HANDLED,
    SUM(f.APPROVED_AMOUNT) AS TOTAL_APPROVED_AMOUNT
FROM SNOW_FACT_CLAIMS f
JOIN SNOW_DIM_HOSPITAL h ON f.HOSPITAL_KEY = h.HOSPITAL_KEY
JOIN SNOW_DIM_NETWORK n ON h.NETWORK_KEY = n.NETWORK_KEY
GROUP BY n.NETWORK_DIRECTOR
ORDER BY TOTAL_CLAIMS_HANDLED DESC;

-- TASK 13 — Data Anomaly Analysis: Master Data Update Test (Network Director Update)
UPDATE STAR_DIM_HOSPITAL
SET NETWORK_DIRECTOR = 'Dr. Anand'
WHERE NETWORK_NAME = 'Apollo Healthcare Group';

UPDATE SNOW_DIM_NETWORK
SET NETWORK_DIRECTOR = 'Dr. Anand'
WHERE NETWORK_ID = 10;

SELECT 'Star Schema' AS SCHEMA_TYPE, 'STAR_DIM_HOSPITAL' AS UPDATED_TABLE,
       (SELECT COUNT(*) FROM STAR_DIM_HOSPITAL WHERE NETWORK_NAME = 'Apollo Healthcare Group') AS ROWS_UPDATED,
       'Higher (Multiple rows)' AS MAINTENANCE_EFFORT
UNION ALL
SELECT 'Snowflake Schema', 'SNOW_DIM_NETWORK',
       (SELECT COUNT(*) FROM SNOW_DIM_NETWORK WHERE NETWORK_ID = 10),
       'Lower (Single row)';

-- TASK 14 — Full Architecture Record Audit & Schema Comparison
SELECT 'Star Schema' AS SCHEMA_TYPE, 'STAR_DIM_HOSPITAL' AS TABLE_NAME, COUNT(*) AS RECORD_COUNT FROM STAR_DIM_HOSPITAL
UNION ALL
SELECT 'Star Schema', 'STAR_DIM_TREATMENT', COUNT(*) FROM STAR_DIM_TREATMENT
UNION ALL
SELECT 'Star Schema', 'STAR_FACT_CLAIMS', COUNT(*) FROM STAR_FACT_CLAIMS
UNION ALL
SELECT 'Snowflake Schema', 'SNOW_DIM_NETWORK', COUNT(*) FROM SNOW_DIM_NETWORK
UNION ALL
SELECT 'Snowflake Schema', 'SNOW_DIM_HOSPITAL', COUNT(*) FROM SNOW_DIM_HOSPITAL
UNION ALL
SELECT 'Snowflake Schema', 'SNOW_DIM_DIAGNOSIS_GROUP', COUNT(*) FROM SNOW_DIM_DIAGNOSIS_GROUP
UNION ALL
SELECT 'Snowflake Schema', 'SNOW_DIM_TREATMENT', COUNT(*) FROM SNOW_DIM_TREATMENT
UNION ALL
SELECT 'Snowflake Schema', 'SNOW_FACT_CLAIMS', COUNT(*) FROM SNOW_FACT_CLAIMS;