-- TASK 1 — Create Database and Schema Context
CREATE WAREHOUSE P12_WH;
USE WAREHOUSE P12_WH;

CREATE DATABASE RETAIL_DW;
USE DATABASE RETAIL_DW; 

CREATE SCHEMA RETAIL_DW.SALES_ANALYTICS;
USE SCHEMA SALES_ANALYTICS;

-- TASK 2 — Create Store Conformed Dimension Table (`DIM_STORE`)
CREATE TABLE DIM_STORE(
    STORE_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    STORE_ID NUMBER,
    STORE_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    STORE_MANAGER VARCHAR(100)
);

-- TASK 3 — Create Product Dimension Table (`DIM_PRODUCT`)
CREATE TABLE DIM_PRODUCT(
    PRODUCT_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    PRODUCT_ID NUMBER,
    PRODUCT_NAME VARCHAR(100),
    CATEGORY VARCHAR(50),
    UNIT_PRICE NUMBER(10,2) 
);

-- TASK 4 — Create Hybrid Customer Dimension Table (`DIM_CUSTOMER_HYBRID`)
CREATE TABLE DIM_CUSTOMER_HYBRID(
    CUSTOMER_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(50),
    PREVIOUS_CITY VARCHAR(50),
    STATE VARCHAR(50),
    CURRENT_MEMBERSHIP VARCHAR(30),
    PREVIOUS_MEMBERSHIP VARCHAR(30),
    HISTORICAL_MEMBERSHIP VARCHAR(30),
    SEGMENT VARCHAR(30),
    EFFECTIVE_DATE DATE,
    EXPIRY_DATE DATE,
    IS_CURRENT BOOLEAN
);

-- TASK 5 — Populate Initial Store and Product Dimension Data
CREATE STAGE P12_STAGE FILE_FORMAT = CSV_FILE;

COPY INTO DIM_STORE(STORE_ID, STORE_NAME, CITY, STATE, STORE_MANAGER)
FROM @P12_STAGE/stores.csv;

COPY INTO DIM_PRODUCT(PRODUCT_ID, PRODUCT_NAME, CATEGORY, UNIT_PRICE)
FROM @P12_STAGE/products.csv;

-- TASK 6 — Populate Initial Customer Dimension Data
COPY INTO DIM_CUSTOMER_HYBRID(CUSTOMER_ID, CUSTOMER_NAME, CITY, PREVIOUS_CITY, STATE, CURRENT_MEMBERSHIP, PREVIOUS_MEMBERSHIP, HISTORICAL_MEMBERSHIP, SEGMENT, EFFECTIVE_DATE, EXPIRY_DATE, IS_CURRENT)
FROM (SELECT $1,$2,$3,NULL,$4,$5,NULL,$5,$6,'2026-01-01','9999-12-31',TRUE FROM @P12_STAGE/customers_initial.csv);

-- TASK 7 — Create Sales Transaction Fact Table (`FACT_SALES`)
CREATE TABLE FACT_SALES(
    SALES_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    TRANSACTION_ID VARCHAR(50),
    TRANSACTION_DATE DATE,
    CUSTOMER_KEY NUMBER REFERENCES DIM_CUSTOMER_HYBRID(CUSTOMER_KEY),
    STORE_KEY NUMBER REFERENCES DIM_STORE(STORE_KEY),
    PRODUCT_KEY NUMBER REFERENCES DIM_PRODUCT(PRODUCT_KEY),
    QUANTITY NUMBER,
    UNIT_PRICE NUMBER(10,2),
    TOTAL_AMOUNT NUMBER(12,2)
);

-- TASK 8 — Insert Q1 2026 Sales Fact Transactions
INSERT INTO FACT_SALES(TRANSACTION_ID, TRANSACTION_DATE, CUSTOMER_KEY, STORE_KEY, PRODUCT_KEY, QUANTITY, UNIT_PRICE, TOTAL_AMOUNT)
SELECT 
    'TXN-1001',
    '2026-02-15',
    C.CUSTOMER_KEY,
    S.STORE_KEY,
    P.PRODUCT_KEY,
    1,
    P.UNIT_PRICE,
    1 * P.UNIT_PRICE
FROM DIM_CUSTOMER_HYBRID C, DIM_PRODUCT P, DIM_STORE S
WHERE C.CUSTOMER_ID = 101
    AND P.PRODUCT_ID = 501
    AND S.STORE_ID = 201
    AND C.IS_CURRENT = TRUE;

INSERT INTO FACT_SALES(TRANSACTION_ID, TRANSACTION_DATE, CUSTOMER_KEY, STORE_KEY, PRODUCT_KEY, QUANTITY, UNIT_PRICE, TOTAL_AMOUNT)
SELECT  
    'TXN-1002',
    '2026-03-10',
    C.CUSTOMER_KEY,
    S.STORE_KEY,
    P.PRODUCT_KEY,
    2,
    P.UNIT_PRICE,
    2 * P.UNIT_PRICE
FROM DIM_CUSTOMER_HYBRID C, DIM_STORE S, DIM_PRODUCT P
WHERE C.CUSTOMER_ID = 103
    AND P.PRODUCT_ID = 502
    AND S.STORE_ID = 203
    AND C.IS_CURRENT = TRUE;

-- TASK 9 — Apply Store Manager Update (SCD Type 1 Overwrite)
UPDATE DIM_STORE
SET
    STORE_MANAGER = 'Suresh Menon'
WHERE STORE_ID = 201;

SELECT * FROM DIM_STORE WHERE STORE_ID = 201;

-- TASK 10 — Execute Multi-Attribute Customer Updates
UPDATE DIM_CUSTOMER_HYBRID
SET 
    EXPIRY_DATE = '2026-03-31',
    IS_CURRENT = FALSE
WHERE CUSTOMER_ID = 101 AND IS_CURRENT = TRUE;

UPDATE DIM_CUSTOMER_HYBRID
SET
    EXPIRY_DATE = '2026-04-04',
    IS_CURRENT = FALSE
WHERE CUSTOMER_ID = 103 AND IS_CURRENT = TRUE;

UPDATE DIM_CUSTOMER_HYBRID
SET
    EXPIRY_DATE = '2026-04-09',
    IS_CURRENT = FALSE
WHERE CUSTOMER_ID = 104 AND IS_CURRENT = TRUE;

CREATE TABLE UPDATED_CUSTOMERS(
    CUSTOMER_ID     NUMBER,
    CUSTOMER_NAME   VARCHAR(100),
    CITY            VARCHAR(50),
    STATE           VARCHAR(50),
    MEMBERSHIP      VARCHAR(30),
    SEGMENT         VARCHAR(30),
    EFFECTIVE_DATE  DATE
);

COPY INTO UPDATED_CUSTOMERS
FROM @P12_STAGE/customer_updates.csv;

INSERT INTO DIM_CUSTOMER_HYBRID
(CUSTOMER_ID, CUSTOMER_NAME, CITY, PREVIOUS_CITY, STATE, CURRENT_MEMBERSHIP, PREVIOUS_MEMBERSHIP, HISTORICAL_MEMBERSHIP, SEGMENT, EFFECTIVE_DATE, EXPIRY_DATE, IS_CURRENT)
SELECT 
    u.CUSTOMER_ID, u.CUSTOMER_NAME, u.CITY, old.CITY, u.STATE,
    u.MEMBERSHIP, old.CURRENT_MEMBERSHIP, u.MEMBERSHIP, u.SEGMENT,
    u.EFFECTIVE_DATE, '9999-12-31', TRUE
FROM UPDATED_CUSTOMERS u
JOIN DIM_CUSTOMER_HYBRID old
    ON old.customer_id = u.customer_id AND old.is_current = FALSE;

UPDATE DIM_CUSTOMER_HYBRID
SET CURRENT_MEMBERSHIP = 'Gold', PREVIOUS_MEMBERSHIP = 'Silver', CITY = 'Bengaluru', PREVIOUS_CITY = 'Hyderabad', STATE = 'Karnataka'
WHERE CUSTOMER_ID = 101;

UPDATE DIM_CUSTOMER_HYBRID
SET CURRENT_MEMBERSHIP = 'Gold', PREVIOUS_MEMBERSHIP = 'Silver', CITY = 'Chennai', PREVIOUS_CITY = 'Vijayawada', STATE = 'Tamil Nadu'
WHERE CUSTOMER_ID = 103;

UPDATE DIM_CUSTOMER_HYBRID
SET CURRENT_MEMBERSHIP = 'Platinum', PREVIOUS_MEMBERSHIP = 'Gold', CITY = 'Hyderabad', STATE = 'Telangana'
WHERE CUSTOMER_ID = 104;

-- TASK 11 — Insert Q2 2026 Sales Transaction
INSERT INTO FACT_SALES (TRANSACTION_ID, TRANSACTION_DATE, CUSTOMER_KEY, STORE_KEY, PRODUCT_KEY, QUANTITY, UNIT_PRICE, TOTAL_AMOUNT)
SELECT
    'TXN-2001',
    '2026-04-15',
    C.CUSTOMER_KEY,
    S.STORE_KEY,
    P.PRODUCT_KEY,
    1,
    P.UNIT_PRICE,
    1 * P.UNIT_PRICE
FROM DIM_CUSTOMER_HYBRID C, DIM_STORE S, DIM_PRODUCT P
WHERE C.CUSTOMER_ID = 101
  AND P.PRODUCT_ID = 503
  AND S.STORE_ID = 201
  AND C.IS_CURRENT = TRUE;


-- TASK 12 — Display Full Customer Dimension History
SELECT CUSTOMER_ID, CUSTOMER_NAME, CITY, PREVIOUS_CITY, CURRENT_MEMBERSHIP,
       PREVIOUS_MEMBERSHIP, HISTORICAL_MEMBERSHIP, SEGMENT, EFFECTIVE_DATE, EXPIRY_DATE, IS_CURRENT
FROM DIM_CUSTOMER_HYBRID
ORDER BY CUSTOMER_ID, EFFECTIVE_DATE;

-- TASK 13 — Point-in-Time Point-of-Sale Analytics Query
SELECT 
    f.TRANSACTION_ID,
    f.TRANSACTION_DATE,
    c.CUSTOMER_ID,
    c.CUSTOMER_NAME,
    c.CITY AS CURRENT_CITY,
    c.HISTORICAL_MEMBERSHIP AS MEMBERSHIP_AT_PURCHASE,
    c.SEGMENT AS SEGMENT_AT_PURCHASE,
    s.STORE_NAME,
    p.PRODUCT_NAME,
    f.TOTAL_AMOUNT
FROM FACT_SALES f
JOIN DIM_PRODUCT p 
    ON p.PRODUCT_KEY = f.PRODUCT_KEY
JOIN DIM_CUSTOMER_HYBRID c
    ON f.customer_key = c.customer_key
JOIN DIM_STORE s
    ON s.store_key = f.store_key
WHERE c.customer_id = 101;

-- TASK 14 — Warehouse Record Count and Data Auditing Validation
SELECT 'STORE DIMENSION RECORDS' AS METRIC, COUNT(*) AS VALUE FROM DIM_STORE
UNION ALL
SELECT 'PRODUCT DIMENSION RECORDS', COUNT(*) FROM DIM_PRODUCT
UNION ALL
SELECT 'TOTAL CUSTOMER DIMENSION RECORDS', COUNT(*) FROM DIM_CUSTOMER_HYBRID
UNION ALL
SELECT 'CURRENT CUSTOMER RECORDS', COUNT(*) FROM DIM_CUSTOMER_HYBRID WHERE IS_CURRENT = TRUE
UNION ALL
SELECT 'HISTORICAL CUSTOMER RECORDS', COUNT(*) FROM DIM_CUSTOMER_HYBRID WHERE IS_CURRENT = FALSE
UNION ALL
SELECT 'FACT SALES TRANSACTIONS', COUNT(*) FROM FACT_SALES;