CREATE WAREHOUSE P14B_WH;

USE WAREHOUSE P14B_WH;

CREATE DATABASE P14B_DB;
USE DATABASE P14B_DB;

CREATE SCHEMA P14B_SCHEMA;
USE SCHEMA P14B_SCHEMA;   

-- TASK 1: Bronze Layer Setup & Ingestion
-- Create table `BRONZE_PAYMENT_PAYLOADS` and ingest all 8 raw JSON records.

CREATE TABLE BRONZE_PAYMENT_PAYLOADS (
    RAW_PAYLOAD VARIANT
);

CREATE FILE FORMAT P14B_JSON_FORMAT
    TYPE = 'JSON'
    STRIP_OUTER_ARRAY = FALSE;

CREATE STAGE P14B_STAGE
    FILE_FORMAT = P14B_JSON_FORMAT;

COPY INTO BRONZE_PAYMENT_PAYLOADS (RAW_PAYLOAD)
FROM @P14B_STAGE;

SELECT COUNT(*) AS TOTAL_BRONZE_RECORDS_CT FROM BRONZE_PAYMENT_PAYLOADS;

-- TASK 2: Silver Layer ETL & Fee Computations
-- - Populate `SILVER_CLEANED_TRANSACTIONS`.
-- - Apply credit card masking: `XXXX-XXXX-XXXX-4444`.
-- - Calculate `PROCESSING_FEE = GROSS_AMOUNT * (FEE_PCT / 100)`
-- - Calculate `NET_SETTLEMENT_AMOUNT = GROSS_AMOUNT - PROCESSING_FEE`
CREATE TABLE SILVER_CLEANED_TRANSACTIONS(
    TXN_ID VARCHAR(10),
    TXN_TIME TIMESTAMP_NTZ,
    MERCHANT_ID NUMBER,
    MERCHANT_NAME VARCHAR(50),
    MASKED_CARD VARCHAR(100),
    GROSS NUMBER(12,2),
    PROCESSING_FEE NUMBER(12,2),
    NET_SETTLEMENT_AMOUNT NUMBER(12,2),
    STATUS VARCHAR(25)
);

INSERT INTO SILVER_CLEANED_TRANSACTIONS
SELECT
    RAW_PAYLOAD:txn_id::VARCHAR(10),
    RAW_PAYLOAD:txn_time::TIMESTAMP_NTZ,
    RAW_PAYLOAD:merchant_id::NUMBER,
    RAW_PAYLOAD:merchant_name::VARCHAR(50),
    'XXXX-XXXX-XXXX-' || RIGHT(RAW_PAYLOAD:card_number::VARCHAR(100),4) AS MASKED_CARD,
    RAW_PAYLOAD:amount::NUMBER(12,2) AS GROSS,
    ROUND(RAW_PAYLOAD:amount::NUMBER(12,2) * (RAW_PAYLOAD:fee_pct::NUMBER(5,2)/100),2) AS PROCESSING_FEE,
    RAW_PAYLOAD:amount::NUMBER(12,2) - ROUND(RAW_PAYLOAD:amount::NUMBER(12,2) * (RAW_PAYLOAD:fee_pct::NUMBER(5,2)/100),2) AS NET_SETTLEMENT_AMOUNT,
    RAW_PAYLOAD:status::VARCHAR(25)
FROM BRONZE_PAYMENT_PAYLOADS;

SELECT TXN_ID, MERCHANT_ID, MERCHANT_NAME, MASKED_CARD, GROSS, PROCESSING_FEE, NET_SETTLEMENT_AMOUNT, STATUS
FROM SILVER_CLEANED_TRANSACTIONS
ORDER BY TXN_ID;

-- TASK 3: Gold Layer Financial Aggregations
-- - Create `GOLD_MERCHANT_SETTLEMENTS` containing aggregated metrics for `STATUS = 'APPROVED'` records.

CREATE TABLE GOLD_MERCHANT_SETTLEMENTS(
    MERCHANT_ID NUMBER,
    MERCHANT_NAME VARCHAR(50),
    TOTAL_APPROVED_GROSS NUMBER(10,2),
    TOTAL_GATEWAY_FEES NUMBER(10,2),
    TOTAL_NET_PAYOUT NUMBER(10,2),
    APPROVED_COUNT NUMBER
);

INSERT INTO GOLD_MERCHANT_SETTLEMENTS
SELECT 
    MERCHANT_ID,
    MERCHANT_NAME,
    SUM(GROSS) AS  TOTAL_APPROVED_GROSS,
    SUM(PROCESSING_FEE) AS TOTAL_GATEWAY_FEES,
    SUM(NET_SETTLEMENT_AMOUNT) AS TOTAL_NET_PAYOUT,
    COUNT(*) AS APPROVED_COUNT
FROM SILVER_CLEANED_TRANSACTIONS
WHERE STATUS = 'APPROVED'
GROUP BY MERCHANT_ID, MERCHANT_NAME;

SELECT * FROM GOLD_MERCHANT_SETTLEMENTS ORDER BY MERCHANT_ID;

-- TASK 4: Data Corruption Simulation & Time-Travel Inspection
-- 1. Run UPDATE setting `TechZone` approved records to `STATUS = 'REFUNDED'`.
-- 2. Execute Time-Travel query (`AT (OFFSET => ...)` or `BEFORE`) to view pre-corruption data.

UPDATE SILVER_CLEANED_TRANSACTIONS
SET
    STATUS = 'REFUNDED'
WHERE MERCHANT_NAME = 'TechZone' AND STATUS = 'APPROVED';

SET corrupt_query_id = (SELECT LAST_QUERY_ID());

SELECT TXN_ID, MERCHANT_NAME, GROSS, STATUS
FROM SILVER_CLEANED_TRANSACTIONS
BEFORE (STATEMENT => $corrupt_query_id)
WHERE MERCHANT_NAME = 'TechZone'
  AND STATUS = 'APPROVED';

-- TASK 5: Time-Travel Recovery Execution
-- - Revert corrupted statuses back to `APPROVED` using Time-Travel data.
UPDATE SILVER_CLEANED_TRANSACTIONS AS current_tbl
SET STATUS = 'APPROVED'
WHERE TXN_ID IN (
    SELECT TXN_ID
    FROM SILVER_CLEANED_TRANSACTIONS
    BEFORE (STATEMENT => $corrupt_query_id)
    WHERE MERCHANT_NAME = 'TechZone'
      AND STATUS = 'APPROVED'
);

SELECT
    MERCHANT_NAME,
    COUNT_IF(STATUS = 'APPROVED')  AS APPROVED_COUNT,
    COUNT_IF(STATUS = 'REFUNDED') AS REFUNDED_COUNT
FROM SILVER_CLEANED_TRANSACTIONS
WHERE MERCHANT_NAME = 'TechZone'
GROUP BY MERCHANT_NAME;

-- TASK 6: End-to-End Pipeline Reconciliation Audit
-- - Write a reconciliation audit query confirming gross totals across all three layers.
SELECT
    (SELECT SUM(RAW_PAYLOAD:amount::NUMBER(12,2)) FROM BRONZE_PAYMENT_PAYLOADS)  AS BRONZE_GROSS_SUM,
    (SELECT SUM(GROSS) FROM SILVER_CLEANED_TRANSACTIONS)                        AS SILVER_GROSS_SUM,
    (SELECT SUM(TOTAL_APPROVED_GROSS) FROM GOLD_MERCHANT_SETTLEMENTS)           AS GOLD_GROSS_SUM,
    CASE
        WHEN (SELECT SUM(RAW_PAYLOAD:amount::NUMBER(12,2)) FROM BRONZE_PAYMENT_PAYLOADS)
             = (SELECT SUM(GROSS) FROM SILVER_CLEANED_TRANSACTIONS)
        THEN TRUE ELSE FALSE
    END AS DATA_MATCH_FLAG;