/*
Problem Description:
The finance team wants to audit high-value customers who spent more on a single order than the total combined revenue generated by any item in the 'Beverages' category. 
Write an SQL query to pull the customer ID, full name, and email.
Use a subquery to find individual order amounts that surpass the maximum value computed from a nested correlated sum calculation of delivered beverage items,
and ensure the customer has never had a cancelled order by integrating an EXCEPT set operator clause.

case=1
output=
customer_id	full_name	email
1	Amit Sharma	amit.sharma@gmail.com
2	Priya Singh	priya.singh@yahoo.com
4	Neha Patel	neha.patel@yahoo.com
5	Arjun Gupta	arjun.gupta@gmail.com



*/
use fs;

SELECT 
    c.customer_id, 
    CONCAT_WS(" ",c.first_name,c.last_name) AS full_name,
    c.email
FROM Customers c
JOIN Orders o
    ON c.customer_id = o.customer_id
WHERE o.total_amount > (SELECT MAX(revenue) FROM (SELECT fi.food_id, SUM(oi.total_amount) AS revenue FROM Orders oi JOIN FoodItems fi ON oi.food_id = fi.food_id WHERE fi.category = "Beverages" AND oi.status = "Delivered" GROUP BY fi.food_id) AS dt)

EXCEPT

SELECT
    c.customer_id,
    CONCAT_WS(" ",c.first_name,c.last_name) AS full_name,
    c.email
FROM Customers c
JOIN Orders o
    ON c.customer_id = o.customer_id
WHERE o.status = "Cancelled";