/*
Problem Description:
The restaurant operations division wants to find out which food items are the primary revenue drivers within each menu section. 
Write a read-only SQL query that constructs a derived table to compute the total revenue generated by each food item 
(filtered only for orders that have been successfully 'Delivered'). 
Combine this with a correlated subquery to filter and return the food item name, category, and total revenue for the food items 
that have achieved the absolute highest revenue within their respective menu category.

case=1
output=
food_item_name	category	total_revenue
Masala Dosa	Breakfast	360.00
Chicken Biryani	Main Course	300.00
Dal Tadka	Main Course	300.00
Samosa	Snacks	270.00
Butter Naan	Breads	240.00
Mango Lassi	Beverages	180.00
Gulab Jamun	Desserts	150.00



*/
use fs;

SELECT 
    dt.food_item_name,
    dt.category,
    dt.total_revenue
FROM (SELECT fi.name AS food_item_name, fi.category AS category, SUM(o.total_amount) AS total_revenue FROM Orders o JOIN FoodItems fi ON o.food_id = fi.food_id WHERE o.status = 'Delivered' GROUP BY fi.name, fi.category) dt
WHERE total_revenue IN (SELECT MAX(dt2.revenue) FROM (SELECT fi.name AS food_item_name, SUM(o.total_amount) AS revenue FROM Orders o JOIN FoodItems fi ON o.food_id = fi.food_id WHERE o.status = 'Delivered' AND fi.category = dt.category GROUP BY fi.name) dt2)
ORDER BY total_revenue DESC;