-- TASK 1: Bronze Data Lake Ingestion & Schema-on-Read Exploration
-- - Create Database: `LOGISTICS_LAKEHOUSE_DB`
-- - Create Schema: `FLEET_CORE`
-- - Create Bronze table `BRONZE_IOT_STREAMS` (`INGEST_ID`, `RAW_PAYLOAD` VARIANT, `RECORDED_AT`).
-- - Ingest valid JSON records into `BRONZE_IOT_STREAMS`.
-- - Write a Schema-on-Read query extracting `payload_id`, `payload_type`, `timestamp`, 
--   vehicle identifiers, and shipment declared values.
CREATE OR REPLACE WAREHOUSE P15_WH;
USE WAREHOUSE P15_WH;

CREATE OR REPLACE DATABASE LOGISTICS_LAKEHOUSE_DB;
USE DATABASE LOGISTICS_LAKEHOUSE_DB;

CREATE OR REPLACE SCHEMA LOGISTICS_LAKEHOUSE_DB.FLEET_CORE;
USE SCHEMA FLEET_CORE;

CREATE OR REPLACE TABLE BRONZE_IOT_STREAMS(
    INGEST_ID INT AUTOINCREMENT,
    RAW_PAYLOAD VARIANT,
    RECORDED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);  

CREATE OR REPLACE FILE FORMAT RAW_TEXT_FORMAT
    TYPE = 'CSV'
    FIELD_DELIMITER = 'NONE'
    RECORD_DELIMITER = '\n';
    
CREATE OR REPLACE STAGE P15_STAGE
    FILE_FORMAT = (FORMAT_NAME = 'RAW_TEXT_FORMAT');

CREATE OR REPLACE TABLE RAW_STAGING (LINE_TEXT VARCHAR);

COPY INTO RAW_STAGING (LINE_TEXT)
FROM @P15_STAGE;

INSERT INTO BRONZE_IOT_STREAMS(RAW_PAYLOAD)
SELECT TRY_PARSE_JSON(LINE_TEXT)
FROM RAW_STAGING
WHERE TRY_PARSE_JSON(LINE_TEXT) IS NOT NULL;

SELECT COUNT(*) AS TOTAL_BRONZE_RECORDS FROM BRONZE_IOT_STREAMS;

SELECT
    RAW_PAYLOAD:payload_id::STRING AS PAYLOAD_ID,
    RAW_PAYLOAD:payload_type::STRING AS PAYLOAD_TYPE,
    RAW_PAYLOAD:timestamp::TIMESTAMP_TZ AS EVENT_TIMESTAMP,
    RAW_PAYLOAD:data:vehicle_id::STRING AS VEHICLE_ID,
    RAW_PAYLOAD:data:shipment_id::STRING AS SHIPMENT_ID,
    RAW_PAYLOAD:data:declared_value::NUMBER(12,2) AS DECLARED_VALUE
FROM BRONZE_IOT_STREAMS
ORDER BY PAYLOAD_ID;

-- TASK 2: Dead-Letter Queue Quarantine Strategy
-- - Create table `QUARANTINE_IOT_PAYLOADS` (`QUARANTINE_ID`, `RAW_RECORD_TEXT`, `REASON`).
-- - Use `TRY_PARSE_JSON` to intercept malformed binary/string entries and populate the quarantine table.
CREATE OR REPLACE TABLE QUARANTINE_IOT_PAYLOADS(
    QUARANTINE_ID INT AUTOINCREMENT,
    RAW_RECORD_TEXT STRING,
    REASON STRING
);

INSERT INTO QUARANTINE_IOT_PAYLOADS(RAW_RECORD_TEXT, REASON)
SELECT
    LINE_TEXT,
    'MALFORMED_JSON_BODY'
FROM RAW_STAGING
WHERE TRY_PARSE_JSON(LINE_TEXT) IS NULL;

SELECT * FROM QUARANTINE_IOT_PAYLOADS;

-- TASK 3: Silver Layer ETL — Schema-on-Write Modeling & Computations
-- - Create Silver table `SILVER_CUSTOMS_CLEARANCE`:
--   * Columns: `SHIPMENT_ID`, `PAYLOAD_ID`, `VEHICLE_ID`, `DESTINATION_COUNTRY`, 
--     `DECLARED_VALUE`, `DUTY_PCT`, `DUTY_AMOUNT_DUE`, `BORDER_CODE`, `CLEARANCE_STATUS`
-- - Build an ETL query targeting `payload_type = 'CUSTOMS'`:
--   * Calculate `DUTY_AMOUNT_DUE = DECLARED_VALUE * (DUTY_PCT / 100)`
--   * Extract `border_clearance_code` into `BORDER_CODE` (handling missing schema fields as NULL).

CREATE OR REPLACE TABLE SILVER_CUSTOMS_CLEARANCE(
    SHIPMENT_ID STRING,
    PAYLOAD_ID STRING,
    VEHICLE_ID STRING, 
    DEST_COUNTRY STRING,
    DECLARED_VALUE NUMBER(12,2),
    DUTY_PCT NUMBER(4,1),
    DUTY_AMOUNT_DUE NUMBER(12,2),
    BORDER_CODE STRING,
    CLEARANCE_STATUS STRING
);

INSERT INTO SILVER_CUSTOMS_CLEARANCE
SELECT
    RAW_PAYLOAD:data:shipment_id::STRING AS SHIPMENT_ID,
    RAW_PAYLOAD:payload_id::STRING AS PAYLOAD_ID,
    RAW_PAYLOAD:data:vehicle_id::STRING AS VEHICLE_ID,
    RAW_PAYLOAD:data:destination_country::STRING AS DEST_COUNTRY,
    RAW_PAYLOAD:data:declared_value::NUMBER(12,2) AS DECLARED_VALUE,
    RAW_PAYLOAD:data:duty_pct::NUMBER(4,1) AS DUTY_PCT,
    ROUND(RAW_PAYLOAD:data:declared_value::NUMBER(12,2) * (RAW_PAYLOAD:data:duty_pct::NUMBER(4,1)/100),2) AS DUTY_AMOUNT_DUE,
    RAW_PAYLOAD:data:border_clearance_code::STRING AS BORDER_CODE,
    RAW_PAYLOAD:data:clearance_status::STRING AS CLEARANCE_STATUS
FROM BRONZE_IOT_STREAMS
WHERE RAW_PAYLOAD:payload_type::STRING = 'CUSTOMS';

SELECT * FROM SILVER_CUSTOMS_CLEARANCE;

-- TASK 4: Gold Layer Strategic Aggregations
-- - Create Gold table `GOLD_COUNTRY_DUTY_SUMMARY` summarizing metrics strictly for 
  -- shipments where `CLEARANCE_STATUS = 'CLEARED'`.

CREATE OR REPLACE TABLE GOLD_COUNTRY_DUTY_SUMMARY(
    DEST_COUNTRY STRING,
    TOTAL_CLEARED_VAL NUMBER(12,2),
    TOTAL_DUTIES_COLLECTED NUMBER(12,2),
    AVG_DUTY_RATE_PCT NUMBER(4,2),
    CLEARED_SHIPMENTS NUMBER
);

INSERT INTO GOLD_COUNTRY_DUTY_SUMMARY
SELECT
    DEST_COUNTRY,
    SUM(DECLARED_VALUE) AS TOTAL_CLEARED_VAL,
    SUM(DUTY_AMOUNT_DUE) AS TOTAL_DUTIES_COLLECTED,
    ROUND(SUM(DUTY_AMOUNT_DUE) / SUM(DECLARED_VALUE) * 100, 2) AS AVG_DUTY_RATE_PCT,
    COUNT(*) AS CLEARED_SHIPMENTS
FROM SILVER_CUSTOMS_CLEARANCE
WHERE CLEARANCE_STATUS = 'CLEARED'
GROUP BY DEST_COUNTRY
ORDER BY DEST_COUNTRY;

SELECT * FROM GOLD_COUNTRY_DUTY_SUMMARY ORDER BY DEST_COUNTRY;

-- TASK 5: Disaster Recovery via Snowflake Time-Travel Auditing
-- 1. Simulate corruption: Run an unauthorized SQL command setting all `CAN` shipments 
--    in `SILVER_CUSTOMS_CLEARANCE` to `CLEARANCE_STATUS = 'REJECTED'`.
-- 2. Write a Time-Travel query using `AT (OFFSET => ...)` or `BEFORE` to view the original values.
-- 3. Write a SQL recovery query restoring `SILVER_CUSTOMS_CLEARANCE` back to its 
--    uncorrupted state.

UPDATE SILVER_CUSTOMS_CLEARANCE
SET CLEARANCE_STATUS = 'REJECTED'
WHERE DEST_COUNTRY = 'CAN';

SET corrupt_query_id = LAST_QUERY_ID();

SELECT *
FROM SILVER_CUSTOMS_CLEARANCE
BEFORE (STATEMENT => $corrupt_query_id);

MERGE INTO SILVER_CUSTOMS_CLEARANCE AS TARGET
USING (
    SELECT *
    FROM SILVER_CUSTOMS_CLEARANCE
    BEFORE (STATEMENT => $corrupt_query_id)
) AS SOURCE
ON TARGET.SHIPMENT_ID = SOURCE.SHIPMENT_ID
WHEN MATCHED THEN UPDATE SET
    TARGET.CLEARANCE_STATUS = SOURCE.CLEARANCE_STATUS;

SELECT
    DEST_COUNTRY,
    COUNT(CASE WHEN CLEARANCE_STATUS = 'CLEARED' THEN 1 END) AS CLEARED_COUNT,
    COUNT(CASE WHEN CLEARANCE_STATUS = 'REJECTED' THEN 1 END) AS REJECTED_COUNT
FROM SILVER_CUSTOMS_CLEARANCE
GROUP BY DEST_COUNTRY
ORDER BY DEST_COUNTRY;

-- TASK 6: End-to-End Pipeline Lineage & Reconciliation Audit
-- Write a cross-layer audit query comparing declared values across Bronze, Silver, and Gold layers 
-- to verify pipeline completeness.
SELECT
    BRONZE_TOTALS.BRONZE_GROSS_TOTAL,
    SILVER_TOTALS.SILVER_GROSS_TOTAL,
    GOLD_TOTALS.GOLD_GROSS_TOTAL,
    (BRONZE_TOTALS.BRONZE_GROSS_TOTAL = SILVER_TOTALS.SILVER_GROSS_TOTAL
     AND GOLD_TOTALS.GOLD_GROSS_TOTAL = SILVER_TOTALS.SILVER_GROSS_TOTAL - EXCLUDED_TOTALS.EXCLUDED_VALUE
    ) AS RECONCILED_FLAG
FROM
    (SELECT SUM(RAW_PAYLOAD:data:declared_value::NUMBER(12,2)) AS BRONZE_GROSS_TOTAL
     FROM BRONZE_IOT_STREAMS
     WHERE RAW_PAYLOAD:payload_type::STRING = 'CUSTOMS') BRONZE_TOTALS,
    (SELECT SUM(DECLARED_VALUE) AS SILVER_GROSS_TOTAL
     FROM SILVER_CUSTOMS_CLEARANCE) SILVER_TOTALS,
    (SELECT SUM(DECLARED_VALUE) AS GOLD_GROSS_TOTAL
     FROM SILVER_CUSTOMS_CLEARANCE
     WHERE CLEARANCE_STATUS = 'CLEARED') GOLD_TOTALS,
    (SELECT SUM(DECLARED_VALUE) AS EXCLUDED_VALUE
     FROM SILVER_CUSTOMS_CLEARANCE
     WHERE CLEARANCE_STATUS != 'CLEARED') EXCLUDED_TOTALS;