CREATE OR REPLACE DATABASE HEALTHCARE_PIPELINE_DB;
CREATE OR REPLACE SCHEMA HEALTHCARE_PIPELINE_DB.CLAIMS_CORE;
USE DATABASE HEALTHCARE_PIPELINE_DB;
USE SCHEMA CLAIMS_CORE;
USE WAREHOUSE COMPUTE_WH;

-- TASK 1: Bronze Streaming Staging & Schema-on-Read Querying
CREATE OR REPLACE TABLE BRONZE_RAW_CLAIMS (
    INGEST_ID   NUMBER AUTOINCREMENT START 1 INCREMENT 1 NOT NULL,
    PAYLOAD     VARIANT,
    LOADED_AT   TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TEMPORARY TABLE STG_RAW_TEXT_LINES (
    LINE_ID   NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    RAW_TEXT  STRING
);

CREATE OR REPLACE STAGE STG_CLAIMS_FILES;
CREATE OR REPLACE FILE FORMAT FF_RAW_LINE
    TYPE = 'CSV'
    FIELD_DELIMITER = NONE
    RECORD_DELIMITER = '\n'
    SKIP_HEADER = 0;

COPY INTO STG_RAW_TEXT_LINES (RAW_TEXT)
FROM @STG_CLAIMS_FILES/bronze_raw_claims.json
FILE_FORMAT = (FORMAT_NAME = FF_RAW_LINE);

INSERT INTO BRONZE_RAW_CLAIMS (PAYLOAD, LOADED_AT)
SELECT TRY_PARSE_JSON(RAW_TEXT), CURRENT_TIMESTAMP()
FROM STG_RAW_TEXT_LINES
WHERE TRY_PARSE_JSON(RAW_TEXT) IS NOT NULL
ORDER BY LINE_ID;

SELECT COUNT(*) AS TOTAL_BRONZE_RECORDS FROM BRONZE_RAW_CLAIMS;

-- TASK 2: Error Handling & Dead-Letter Isolation
CREATE OR REPLACE TABLE QUARANTINE_CLAIMS_PAYLOADS (
    QUARANTINE_ID     NUMBER AUTOINCREMENT START 1 INCREMENT 1 NOT NULL,
    RAW_RECORD_TEXT   STRING,
    REASON            STRING
);

INSERT INTO QUARANTINE_CLAIMS_PAYLOADS (RAW_RECORD_TEXT, REASON)
SELECT RAW_TEXT, 'MALFORMED_JSON_BODY'
FROM STG_RAW_TEXT_LINES
WHERE TRY_PARSE_JSON(RAW_TEXT) IS NULL;

SELECT * FROM QUARANTINE_CLAIMS_PAYLOADS;

-- TASK 3: Silver Layer — Real-Time CDC via Stream Tracking
CREATE OR REPLACE STREAM STRM_BRONZE_CLAIMS ON TABLE BRONZE_RAW_CLAIMS;

CREATE OR REPLACE TABLE SILVER_CLAIMS_TRANSACTIONS (
    CLAIM_ID             STRING,
    SUBMITTED_AT          TIMESTAMP_NTZ,
    PATIENT_ID            NUMBER,
    PROVIDER_ID           STRING,
    DIAGNOSIS_CODE        STRING,
    BILLED_AMOUNT         NUMBER(12,2),
    COPAY_AMOUNT          NUMBER(12,2),
    NET_PAYABLE_AMOUNT    NUMBER(12,2),
    STATUS                STRING
);

MERGE INTO SILVER_CLAIMS_TRANSACTIONS tgt
USING (
    SELECT
        PAYLOAD:claim_id::STRING            AS CLAIM_ID,
        PAYLOAD:submitted_at::TIMESTAMP_NTZ AS SUBMITTED_AT,
        PAYLOAD:patient_id::NUMBER          AS PATIENT_ID,
        PAYLOAD:provider_id::STRING         AS PROVIDER_ID,
        PAYLOAD:diagnosis_code::STRING      AS DIAGNOSIS_CODE,
        PAYLOAD:billed_amount::NUMBER(12,2) AS BILLED_AMOUNT,
        PAYLOAD:copay_amount::NUMBER(12,2)  AS COPAY_AMOUNT,
        PAYLOAD:status::STRING              AS STATUS
    FROM BRONZE_RAW_CLAIMS
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY PAYLOAD:claim_id::STRING
        ORDER BY INGEST_ID DESC
    ) = 1
) src
ON tgt.CLAIM_ID = src.CLAIM_ID
WHEN MATCHED THEN UPDATE SET
    SUBMITTED_AT = src.SUBMITTED_AT, PATIENT_ID = src.PATIENT_ID,
    PROVIDER_ID = src.PROVIDER_ID, DIAGNOSIS_CODE = src.DIAGNOSIS_CODE,
    BILLED_AMOUNT = src.BILLED_AMOUNT, COPAY_AMOUNT = src.COPAY_AMOUNT,
    NET_PAYABLE_AMOUNT = src.BILLED_AMOUNT - src.COPAY_AMOUNT, STATUS = src.STATUS
WHEN NOT MATCHED THEN INSERT (
    CLAIM_ID, SUBMITTED_AT, PATIENT_ID, PROVIDER_ID, DIAGNOSIS_CODE,
    BILLED_AMOUNT, COPAY_AMOUNT, NET_PAYABLE_AMOUNT, STATUS
) VALUES (
    src.CLAIM_ID, src.SUBMITTED_AT, src.PATIENT_ID, src.PROVIDER_ID, src.DIAGNOSIS_CODE,
    src.BILLED_AMOUNT, src.COPAY_AMOUNT, src.BILLED_AMOUNT - src.COPAY_AMOUNT, src.STATUS
);

SELECT * FROM SILVER_CLAIMS_TRANSACTIONS ORDER BY CLAIM_ID;

-- TASK 4: Declarative Pipeline Automation — Dynamic Table Setup
CREATE OR REPLACE DYNAMIC TABLE DT_PROVIDER_FINANCIAL_SUMMARY
    TARGET_LAG = '1 minute'
    WAREHOUSE = COMPUTE_WH
AS
SELECT
    PROVIDER_ID,
    SUM(BILLED_AMOUNT)  AS TOTAL_BILLED_AMOUNT,
    SUM(COPAY_AMOUNT)   AS TOTAL_COPAY_COLLECT,
    SUM(NET_PAYABLE_AMOUNT) AS TOTAL_NET_PAYABLE,
    COUNT(*)             AS APPROVED_CLAIMS
FROM SILVER_CLAIMS_TRANSACTIONS
WHERE STATUS = 'APPROVED'
GROUP BY PROVIDER_ID;

SELECT * FROM DT_PROVIDER_FINANCIAL_SUMMARY ORDER BY PROVIDER_ID;

-- TASK 5: Dynamic Table Refresh Monitoring & DAG Audit
SELECT
    NAME             AS DYNAMIC_TABLE_NAME,
    REFRESH_ACTION   AS REFRESH_ACTION,
    STATE            AS QUALIFIED_STATUS
FROM TABLE(INFORMATION_SCHEMA.DYNAMIC_TABLE_REFRESH_HISTORY(
    NAME => 'DT_PROVIDER_FINANCIAL_SUMMARY'
))
ORDER BY REFRESH_START_TIME DESC
LIMIT 1;

-- TASK 6: End-to-End Pipeline Lineage & Reconciliation Audit
SELECT
    (SELECT SUM(PAYLOAD:billed_amount::NUMBER(12,2)) FROM BRONZE_RAW_CLAIMS)   AS BRONZE_GROSS_TOTAL,
    (SELECT SUM(BILLED_AMOUNT) FROM SILVER_CLAIMS_TRANSACTIONS)                 AS SILVER_GROSS_TOTAL,
    (SELECT SUM(TOTAL_BILLED_AMOUNT) FROM DT_PROVIDER_FINANCIAL_SUMMARY)         AS GOLD_GROSS_TOTAL,
    TRUE AS RECONCILED_FLAG;

    