-- TASK 1 — Database & Schema Context
CREATE WAREHOUSE P13_WH;
USE WAREHOUSE P13_WH;

CREATE DATABASE RETAIL_SCHEMAS_DW;
USE DATABASE RETAIL_SCHEMAS_DW;

CREATE SCHEMA SCHEMA_COMPARISON;
USE SCHEMA SCHEMA_COMPARISON;

-- TASK 2 — STAR_DIM_STORE
CREATE TABLE STAR_DIM_STORE (
    STORE_KEY        NUMBER AUTOINCREMENT PRIMARY KEY,
    STORE_ID         NUMBER,
    STORE_NAME       VARCHAR(100),
    CITY             VARCHAR(50),
    STATE            VARCHAR(50),
    REGION_NAME      VARCHAR(50),
    REGIONAL_MANAGER VARCHAR(100)
);

-- TASK 3 — STAR_DIM_PRODUCT
CREATE TABLE STAR_DIM_PRODUCT (
    PRODUCT_KEY      NUMBER AUTOINCREMENT PRIMARY KEY,
    PRODUCT_ID       NUMBER,
    PRODUCT_NAME     VARCHAR(100),
    SUBCATEGORY_NAME VARCHAR(50),
    CATEGORY_NAME    VARCHAR(50),
    UNIT_PRICE       NUMBER(10,2)
);

CREATE TABLE STAR_FACT_SALES (
    SALES_KEY        NUMBER AUTOINCREMENT PRIMARY KEY,
    TRANSACTION_ID   VARCHAR(50),
    TRANSACTION_DATE DATE,
    CUSTOMER_ID      NUMBER,
    STORE_KEY        NUMBER,
    PRODUCT_KEY      NUMBER,
    QUANTITY         NUMBER,
    TOTAL_AMOUNT     NUMBER(12,2)
);

-- TASK 4 — Load Star dims + create STAR_FACT_SALES
CREATE FILE FORMAT CSV_FORMAT
    TYPE = 'CSV'
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"';

CREATE STAGE P13_STAGE
    FILE_FORMAT = CSV_FORMAT;

COPY INTO STAR_DIM_STORE (STORE_ID, STORE_NAME, CITY, STATE, REGION_NAME, REGIONAL_MANAGER)
FROM @P13_STAGE/regions_and_stores.csv;

COPY INTO STAR_DIM_PRODUCT (PRODUCT_ID, PRODUCT_NAME, SUBCATEGORY_NAME, CATEGORY_NAME, UNIT_PRICE)
FROM @P13_STAGE/product_hierarchy.csv;

SELECT COUNT(*) AS TOTAL_STORES FROM STAR_DIM_STORE;     
SELECT COUNT(*) AS TOTAL_PRODUCTS FROM STAR_DIM_PRODUCT; 

-- TASK 5 — Load Star Schema Fact Data
CREATE TABLE STG_SALES_TRANSACTIONS (
    TRANSACTION_ID   VARCHAR(50),
    TRANSACTION_DATE DATE,
    CUSTOMER_ID      NUMBER,
    STORE_ID         NUMBER,
    PRODUCT_ID       NUMBER,
    QUANTITY         NUMBER,
    UNIT_PRICE       NUMBER(10,2)
);

COPY INTO STG_SALES_TRANSACTIONS
FROM @P13_STAGE/sales_transactions.csv;

INSERT INTO STAR_FACT_SALES (TRANSACTION_ID, TRANSACTION_DATE, CUSTOMER_ID, STORE_KEY, PRODUCT_KEY, QUANTITY, TOTAL_AMOUNT)
SELECT
    t.TRANSACTION_ID,
    t.TRANSACTION_DATE,
    t.CUSTOMER_ID,
    s.STORE_KEY,
    p.PRODUCT_KEY,
    t.QUANTITY,
    t.QUANTITY * t.UNIT_PRICE AS TOTAL_AMOUNT
FROM STG_SALES_TRANSACTIONS t
JOIN STAR_DIM_STORE s   ON t.STORE_ID = s.STORE_ID
JOIN STAR_DIM_PRODUCT p ON t.PRODUCT_ID = p.PRODUCT_ID;

-- TASK 6 — Build Normalized Snowflake Schema Store Hierarchy
CREATE TABLE SNOW_DIM_REGION (
    REGION_KEY       NUMBER AUTOINCREMENT PRIMARY KEY,
    REGION_NAME      VARCHAR(50),
    REGIONAL_MANAGER VARCHAR(100)
);

CREATE TABLE SNOW_DIM_STORE (
    STORE_KEY   NUMBER AUTOINCREMENT PRIMARY KEY,
    STORE_ID    NUMBER,
    STORE_NAME  VARCHAR(100),
    CITY        VARCHAR(50),
    STATE       VARCHAR(50),
    REGION_KEY  NUMBER REFERENCES SNOW_DIM_REGION(REGION_KEY)
);

-- TASK 7 — Build Normalized Snowflake Schema Product Hierarchy
CREATE TABLE SNOW_DIM_CATEGORY (
    CATEGORY_KEY  NUMBER AUTOINCREMENT PRIMARY KEY,
    CATEGORY_NAME VARCHAR(50)
);

CREATE TABLE SNOW_DIM_SUBCATEGORY (
    SUBCATEGORY_KEY  NUMBER AUTOINCREMENT PRIMARY KEY,
    SUBCATEGORY_NAME VARCHAR(50),
    CATEGORY_KEY     NUMBER REFERENCES SNOW_DIM_CATEGORY(CATEGORY_KEY)
);

CREATE TABLE SNOW_DIM_PRODUCT (
    PRODUCT_KEY     NUMBER AUTOINCREMENT PRIMARY KEY,
    PRODUCT_ID      NUMBER,
    PRODUCT_NAME    VARCHAR(100),
    UNIT_PRICE      NUMBER(10,2),
    SUBCATEGORY_KEY NUMBER REFERENCES SNOW_DIM_SUBCATEGORY(SUBCATEGORY_KEY)
);

-- TASK 8 — Populate Snowflake Schema Normalized Dimensions
CREATE TABLE STG_REGIONS_STORES (
    STORE_ID         NUMBER,
    STORE_NAME       VARCHAR(100),
    CITY             VARCHAR(50),
    STATE            VARCHAR(50),
    REGION_NAME      VARCHAR(50),
    REGIONAL_MANAGER VARCHAR(100)
);

COPY INTO STG_REGIONS_STORES
FROM @P13_STAGE/regions_and_stores.csv;

CREATE TABLE STG_PRODUCT_HIERARCHY (
    PRODUCT_ID       NUMBER,
    PRODUCT_NAME     VARCHAR(100),
    SUBCATEGORY_NAME VARCHAR(50),
    CATEGORY_NAME    VARCHAR(50),
    UNIT_PRICE       NUMBER(10,2)
);

COPY INTO STG_PRODUCT_HIERARCHY
FROM @P13_STAGE/product_hierarchy.csv;

INSERT INTO SNOW_DIM_REGION (REGION_NAME, REGIONAL_MANAGER)
SELECT DISTINCT REGION_NAME, REGIONAL_MANAGER
FROM STG_REGIONS_STORES;

INSERT INTO SNOW_DIM_STORE (STORE_ID, STORE_NAME, CITY, STATE, REGION_KEY)
SELECT s.STORE_ID, s.STORE_NAME, s.CITY, s.STATE, r.REGION_KEY
FROM STG_REGIONS_STORES s
JOIN SNOW_DIM_REGION r ON s.REGION_NAME = r.REGION_NAME;

INSERT INTO SNOW_DIM_CATEGORY (CATEGORY_NAME)
SELECT DISTINCT CATEGORY_NAME
FROM STG_PRODUCT_HIERARCHY;

INSERT INTO SNOW_DIM_SUBCATEGORY (SUBCATEGORY_NAME, CATEGORY_KEY)
SELECT DISTINCT ph.SUBCATEGORY_NAME, c.CATEGORY_KEY
FROM STG_PRODUCT_HIERARCHY ph
JOIN SNOW_DIM_CATEGORY c ON ph.CATEGORY_NAME = c.CATEGORY_NAME;

INSERT INTO SNOW_DIM_PRODUCT (PRODUCT_ID, PRODUCT_NAME, UNIT_PRICE, SUBCATEGORY_KEY)
SELECT ph.PRODUCT_ID, ph.PRODUCT_NAME, ph.UNIT_PRICE, sc.SUBCATEGORY_KEY
FROM STG_PRODUCT_HIERARCHY ph
JOIN SNOW_DIM_SUBCATEGORY sc ON ph.SUBCATEGORY_NAME = sc.SUBCATEGORY_NAME;

SELECT COUNT(*) AS TOTAL_REGIONS FROM SNOW_DIM_REGION;            
SELECT COUNT(*) AS TOTAL_STORES FROM SNOW_DIM_STORE;              
SELECT COUNT(*) AS TOTAL_CATEGORIES FROM SNOW_DIM_CATEGORY;       
SELECT COUNT(*) AS TOTAL_SUBCATEGORIES FROM SNOW_DIM_SUBCATEGORY; 
SELECT COUNT(*) AS TOTAL_PRODUCTS FROM SNOW_DIM_PRODUCT;  

-- TASK 9 — Create Snowflake Schema Fact Table (`SNOW_FACT_SALES`) & Load Data
CREATE TABLE SNOW_FACT_SALES (
    SALES_KEY        NUMBER AUTOINCREMENT PRIMARY KEY,
    TRANSACTION_ID   VARCHAR(50),
    TRANSACTION_DATE DATE,
    CUSTOMER_ID      NUMBER,
    STORE_KEY        NUMBER REFERENCES SNOW_DIM_STORE(STORE_KEY),
    PRODUCT_KEY      NUMBER REFERENCES SNOW_DIM_PRODUCT(PRODUCT_KEY),
    QUANTITY         NUMBER,
    TOTAL_AMOUNT     NUMBER(12,2)
);

INSERT INTO SNOW_FACT_SALES (TRANSACTION_ID, TRANSACTION_DATE, CUSTOMER_ID, STORE_KEY, PRODUCT_KEY, QUANTITY, TOTAL_AMOUNT)
SELECT
    t.TRANSACTION_ID,
    t.TRANSACTION_DATE,
    t.CUSTOMER_ID,
    s.STORE_KEY,
    p.PRODUCT_KEY,
    t.QUANTITY,
    t.QUANTITY * t.UNIT_PRICE AS TOTAL_AMOUNT
FROM STG_SALES_TRANSACTIONS t
JOIN SNOW_DIM_STORE s   ON t.STORE_ID = s.STORE_ID
JOIN SNOW_DIM_PRODUCT p ON t.PRODUCT_ID = p.PRODUCT_ID;

SELECT COUNT(*) AS TOTAL_SALES_ROWS FROM SNOW_FACT_SALES;

-- TASK 10 — Star Schema Analytics Query (Single-Hop Join Performance)
SELECT
    d.REGION_NAME,
    p.CATEGORY_NAME,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM STAR_FACT_SALES f
JOIN STAR_DIM_STORE d   ON f.STORE_KEY = d.STORE_KEY
JOIN STAR_DIM_PRODUCT p ON f.PRODUCT_KEY = p.PRODUCT_KEY
GROUP BY d.REGION_NAME, p.CATEGORY_NAME
ORDER BY d.REGION_NAME, p.CATEGORY_NAME;

-- TASK 11 — Snowflake Schema Analytics Query (Multi-Hop Normalized Join)
SELECT
    r.REGION_NAME,
    c.CATEGORY_NAME,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM SNOW_FACT_SALES f
JOIN SNOW_DIM_STORE s        ON f.STORE_KEY = s.STORE_KEY
JOIN SNOW_DIM_REGION r        ON s.REGION_KEY = r.REGION_KEY
JOIN SNOW_DIM_PRODUCT p       ON f.PRODUCT_KEY = p.PRODUCT_KEY
JOIN SNOW_DIM_SUBCATEGORY sc  ON p.SUBCATEGORY_KEY = sc.SUBCATEGORY_KEY
JOIN SNOW_DIM_CATEGORY c      ON sc.CATEGORY_KEY = c.CATEGORY_KEY
GROUP BY r.REGION_NAME, c.CATEGORY_NAME
ORDER BY r.REGION_NAME, c.CATEGORY_NAME;

-- TASK 13 — Regional Manager Sales Performance Report
SELECT
    d.REGIONAL_MANAGER,
    SUM(f.QUANTITY)     AS TOTAL_ITEMS_SOLD,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_SALES_AMOUNT
FROM STAR_FACT_SALES f
JOIN STAR_DIM_STORE d ON f.STORE_KEY = d.STORE_KEY
GROUP BY d.REGIONAL_MANAGER
ORDER BY TOTAL_SALES_AMOUNT DESC;

-- TASK 14 — Full Warehouse Architecture Audit & Record Count Verification
SELECT 'Star Schema' AS SCHEMA_TYPE, 'STAR_DIM_STORE' AS TABLE_NAME, COUNT(*) AS RECORD_COUNT FROM STAR_DIM_STORE
UNION ALL SELECT 'Star Schema', 'STAR_DIM_PRODUCT', COUNT(*) FROM STAR_DIM_PRODUCT
UNION ALL SELECT 'Star Schema', 'STAR_FACT_SALES', COUNT(*) FROM STAR_FACT_SALES
UNION ALL SELECT 'Snowflake Schema', 'SNOW_DIM_REGION', COUNT(*) FROM SNOW_DIM_REGION
UNION ALL SELECT 'Snowflake Schema', 'SNOW_DIM_STORE', COUNT(*) FROM SNOW_DIM_STORE
UNION ALL SELECT 'Snowflake Schema', 'SNOW_DIM_CATEGORY', COUNT(*) FROM SNOW_DIM_CATEGORY
UNION ALL SELECT 'Snowflake Schema', 'SNOW_DIM_SUBCATEGORY', COUNT(*) FROM SNOW_DIM_SUBCATEGORY
UNION ALL SELECT 'Snowflake Schema', 'SNOW_DIM_PRODUCT', COUNT(*) FROM SNOW_DIM_PRODUCT
UNION ALL SELECT 'Snowflake Schema', 'SNOW_FACT_SALES', COUNT(*) FROM SNOW_FACT_SALES;
