-- TASK 1 — Create Database and Schema
CREATE WAREHOUSE P9_WH;
USE WAREHOUSE P9_WH;

CREATE DATABASE P9_DB;
CREATE SCHEMA P9_DB.P9_SCHEMA;
USE DATABASE P9_DB;
USE SCHEMA P9_SCHEMA;

-- TASK 2 — Create SCD Type 1 Table
CREATE TABLE DIM_CUSTOMER_TYPE1 (
    CUSTOMER_KEY   INT AUTOINCREMENT,
    CUSTOMER_ID    INT,
    CUSTOMER_NAME  VARCHAR(100),
    CITY           VARCHAR(50),
    STATE          VARCHAR(50),
    MEMBERSHIP     VARCHAR(30),
    SEGMENT        VARCHAR(30)
);

CREATE FILE FORMAT CSV_FILE
    TYPE = 'CSV'
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"';

CREATE STAGE P9_STAGE FILE_FORMAT = CSV_FILE;
    
-- TASK 3 — Load Initial Type 1 Data
COPY INTO DIM_CUSTOMER_TYPE1 (CUSTOMER_ID, CUSTOMER_NAME, CITY, STATE, MEMBERSHIP, SEGMENT)
FROM (
    SELECT $1, $2, $3, $4, $5, $6
    FROM @P9_STAGE/customers_initial.csv
);

-- TASK 4 — Apply SCD Type 1 Updates
CREATE TABLE CUSTOMER_UPDATES (
    CUSTOMER_ID     INT,
    CUSTOMER_NAME   VARCHAR(100),
    CITY            VARCHAR(50),
    STATE           VARCHAR(50),
    MEMBERSHIP      VARCHAR(30),
    SEGMENT         VARCHAR(30),
    EFFECTIVE_DATE  DATE
);

COPY INTO CUSTOMER_UPDATES (CUSTOMER_ID, CUSTOMER_NAME, CITY, STATE, MEMBERSHIP, SEGMENT, EFFECTIVE_DATE)
FROM (
    SELECT $1, $2, $3, $4, $5, $6, $7
    FROM @P9_STAGE/customer_updates.csv
);

UPDATE DIM_CUSTOMER_TYPE1 AS tgt
SET CITY = src.CITY,
    STATE = src.STATE,
    MEMBERSHIP = src.MEMBERSHIP,
    SEGMENT = src.SEGMENT
FROM CUSTOMER_UPDATES AS src
WHERE tgt.CUSTOMER_ID = src.CUSTOMER_ID;

-- TASK 5 — Display Type 1 Result
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT
FROM DIM_CUSTOMER_TYPE1
ORDER BY CUSTOMER_ID;

-- TASK 6 — Demonstrate Type 1 History Loss
SELECT
    CUSTOMER_ID,
    CITY,
    STATE,
    MEMBERSHIP
FROM DIM_CUSTOMER_TYPE1
WHERE CUSTOMER_ID = 101;

-- TASK 7 — Create SCD Type 2 Table
CREATE TABLE DIM_CUSTOMER_TYPE2 (
    CUSTOMER_KEY    NUMBER AUTOINCREMENT,
    CUSTOMER_ID     NUMBER,
    CUSTOMER_NAME   VARCHAR(100),
    CITY            VARCHAR(50),
    STATE           VARCHAR(50),
    MEMBERSHIP      VARCHAR(30),
    SEGMENT         VARCHAR(30),
    EFFECTIVE_DATE  DATE,
    EXPIRY_DATE     DATE,
    IS_CURRENT      BOOLEAN
);

-- TASK 8 — Create Type 2 Table
DESCRIBE TABLE DIM_CUSTOMER_TYPE2;

-- TASK 9 — Load Initial Type 2 Records
INSERT INTO DIM_CUSTOMER_TYPE2 (
    CUSTOMER_ID, CUSTOMER_NAME, CITY, STATE, MEMBERSHIP, SEGMENT,
    EFFECTIVE_DATE, EXPIRY_DATE, IS_CURRENT
)
SELECT
    $1, $2, $3, $4, $5, $6,
    '2026-01-01', '9999-12-31', TRUE
FROM @P9_STAGE/customers_initial.csv
(FILE_FORMAT => 'CSV_FILE');

-- TASK 10 — Apply Type 2 Changes
UPDATE DIM_CUSTOMER_TYPE2 AS tgt
SET IS_CURRENT   = FALSE,
    EXPIRY_DATE  = DATEADD(day, -1, src.EFFECTIVE_DATE)
FROM CUSTOMER_UPDATES AS src
WHERE tgt.CUSTOMER_ID = src.CUSTOMER_ID
  AND tgt.IS_CURRENT  = TRUE;

INSERT INTO DIM_CUSTOMER_TYPE2 (
    CUSTOMER_ID, CUSTOMER_NAME, CITY, STATE, MEMBERSHIP, SEGMENT,
    EFFECTIVE_DATE, EXPIRY_DATE, IS_CURRENT
)
SELECT
    CUSTOMER_ID, CUSTOMER_NAME, CITY, STATE, MEMBERSHIP, SEGMENT,
    EFFECTIVE_DATE, '9999-12-31', TRUE
FROM CUSTOMER_UPDATES;

-- TASK 11 — Customer 101 Type 2 Change
SELECT CUSTOMER_ID, CITY, MEMBERSHIP, EFFECTIVE_DATE, EXPIRY_DATE, IS_CURRENT
FROM DIM_CUSTOMER_TYPE2
WHERE CUSTOMER_ID = 101
ORDER BY EFFECTIVE_DATE;

-- TASK 12 — Customer 103 Type 2 Change
SELECT CUSTOMER_ID, CITY, MEMBERSHIP, EFFECTIVE_DATE, EXPIRY_DATE, IS_CURRENT
FROM DIM_CUSTOMER_TYPE2
WHERE CUSTOMER_ID = 103
ORDER BY EFFECTIVE_DATE;

-- TASK 13 — Customer 104 Type 2 Change
SELECT CUSTOMER_ID, CITY, MEMBERSHIP, EFFECTIVE_DATE, EXPIRY_DATE, IS_CURRENT
FROM DIM_CUSTOMER_TYPE2
WHERE CUSTOMER_ID = 104
ORDER BY EFFECTIVE_DATE;

-- TASK 14 — Display Complete Type 2 History
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_TYPE2
ORDER BY CUSTOMER_ID, EFFECTIVE_DATE;

-- TASK 15 — Display Current Customer Records
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT
FROM DIM_CUSTOMER_TYPE2
WHERE IS_CURRENT = TRUE
ORDER BY CUSTOMER_ID;

-- TASK 16 — Historical Customer Analysis
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    MEMBERSHIP,
    CITY,
    EFFECTIVE_DATE,
    EXPIRY_DATE
FROM DIM_CUSTOMER_TYPE2
WHERE CUSTOMER_ID = 101
  AND '2026-03-15' BETWEEN EFFECTIVE_DATE AND EXPIRY_DATE;

-- TASK 18 — Final Validation
SELECT COUNT(*) AS "SCD TYPE 1 RECORD COUNT" FROM DIM_CUSTOMER_TYPE1;
SELECT COUNT(*) AS "SCD TYPE 2 RECORD COUNT" FROM DIM_CUSTOMER_TYPE2;
SELECT COUNT(*) AS "SCD TYPE 2 CURRENT RECORD COUNT" FROM DIM_CUSTOMER_TYPE2 WHERE IS_CURRENT = TRUE;
SELECT COUNT(*) AS "SCD TYPE 2 HISTORICAL RECORD COUNT" FROM DIM_CUSTOMER_TYPE2 WHERE IS_CURRENT = FALSE;