-- TASK 1: Bronze Storage Setup & Error Isolation
CREATE OR REPLACE DATABASE FINANCIAL_GOVERNANCE_DB;
CREATE OR REPLACE SCHEMA FINANCIAL_GOVERNANCE_DB.WEALTH_CORE;
USE DATABASE FINANCIAL_GOVERNANCE_DB;
USE SCHEMA WEALTH_CORE;
USE WAREHOUSE COMPUTE_WH;

CREATE OR REPLACE TABLE BRONZE_BANK_PAYLOADS (
    INGEST_ID   NUMBER AUTOINCREMENT START 1 INCREMENT 1 NOT NULL,
    PAYLOAD     VARIANT,
    LOADED_AT   TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TEMPORARY TABLE STG_RAW_TEXT_LINES (
    LINE_ID   NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    RAW_TEXT  STRING
);

CREATE OR REPLACE STAGE STG_BANK_FILES;
CREATE OR REPLACE FILE FORMAT FF_RAW_LINE
    TYPE = 'CSV'
    FIELD_DELIMITER = NONE
    RECORD_DELIMITER = '\n'
    SKIP_HEADER = 0;

COPY INTO STG_RAW_TEXT_LINES (RAW_TEXT)
FROM @STG_BANK_FILES/bronze_bank_payloads.json
FILE_FORMAT = (FORMAT_NAME = FF_RAW_LINE);

INSERT INTO BRONZE_BANK_PAYLOADS (PAYLOAD, LOADED_AT)
SELECT TRY_PARSE_JSON(RAW_TEXT), CURRENT_TIMESTAMP()
FROM STG_RAW_TEXT_LINES
WHERE TRY_PARSE_JSON(RAW_TEXT) IS NOT NULL
ORDER BY LINE_ID;

SELECT COUNT(*) AS TOTAL_BRONZE_RECORDS FROM BRONZE_BANK_PAYLOADS;

CREATE OR REPLACE TABLE QUARANTINE_GOVERNANCE_PAYLOADS (
    QUARANTINE_ID     NUMBER AUTOINCREMENT START 1 INCREMENT 1 NOT NULL,
    RAW_RECORD_TEXT   STRING,
    REASON            STRING
);

INSERT INTO QUARANTINE_GOVERNANCE_PAYLOADS (RAW_RECORD_TEXT, REASON)
SELECT RAW_TEXT, 'MALFORMED_JSON_BODY'
FROM STG_RAW_TEXT_LINES
WHERE TRY_PARSE_JSON(RAW_TEXT) IS NULL;

SELECT * FROM QUARANTINE_GOVERNANCE_PAYLOADS;

-- TASK 2: Silver Layer Setup & RBAC Role Provisioning
CREATE OR REPLACE TABLE SILVER_BANK_TRANSACTIONS (
    TXN_ID           STRING,
    CLIENT_ID        NUMBER,
    CLIENT_SSN       STRING,
    REGION           STRING,
    ACCOUNT_NO       STRING,
    AMOUNT           NUMBER(18,2),
    STATUS           STRING,
    AML_RISK_SCORE   STRING
);

INSERT INTO SILVER_BANK_TRANSACTIONS
SELECT
    PAYLOAD:txn_id::STRING           AS TXN_ID,
    PAYLOAD:client_id::NUMBER        AS CLIENT_ID,
    PAYLOAD:client_ssn::STRING       AS CLIENT_SSN,
    PAYLOAD:region::STRING           AS REGION,
    PAYLOAD:account_no::STRING       AS ACCOUNT_NO,
    PAYLOAD:amount::NUMBER(18,2)     AS AMOUNT,
    PAYLOAD:status::STRING           AS STATUS,
    PAYLOAD:aml_risk_score::STRING   AS AML_RISK_SCORE
FROM BRONZE_BANK_PAYLOADS;

CREATE ROLE IF NOT EXISTS COMPLIANCE_OFFICER;
CREATE ROLE IF NOT EXISTS NA_ANALYST;
CREATE ROLE IF NOT EXISTS EU_ANALYST;

GRANT USAGE ON DATABASE FINANCIAL_GOVERNANCE_DB TO ROLE COMPLIANCE_OFFICER;
GRANT USAGE ON DATABASE FINANCIAL_GOVERNANCE_DB TO ROLE NA_ANALYST;
GRANT USAGE ON DATABASE FINANCIAL_GOVERNANCE_DB TO ROLE EU_ANALYST;

GRANT USAGE ON SCHEMA WEALTH_CORE TO ROLE COMPLIANCE_OFFICER;
GRANT USAGE ON SCHEMA WEALTH_CORE TO ROLE NA_ANALYST;
GRANT USAGE ON SCHEMA WEALTH_CORE TO ROLE EU_ANALYST;

GRANT SELECT ON TABLE SILVER_BANK_TRANSACTIONS TO ROLE COMPLIANCE_OFFICER;
GRANT SELECT ON TABLE SILVER_BANK_TRANSACTIONS TO ROLE NA_ANALYST;
GRANT SELECT ON TABLE SILVER_BANK_TRANSACTIONS TO ROLE EU_ANALYST;

GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE COMPLIANCE_OFFICER;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE NA_ANALYST;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE EU_ANALYST;

GRANT ROLE COMPLIANCE_OFFICER TO ROLE SYSADMIN;
GRANT ROLE NA_ANALYST TO ROLE SYSADMIN;
GRANT ROLE EU_ANALYST TO ROLE SYSADMIN;

GRANT ROLE COMPLIANCE_OFFICER TO USER GJ;
GRANT ROLE NA_ANALYST TO USER GJ;
GRANT ROLE EU_ANALYST TO USER GJ;

SELECT COUNT(*) AS TOTAL_SILVER_RECORDS FROM SILVER_BANK_TRANSACTIONS;

-- TASK 3: Dynamic Data Masking (DDM) Implementation
CREATE OR REPLACE MASKING POLICY MASK_SSN AS (VAL STRING) RETURNS STRING ->
    CASE WHEN CURRENT_ROLE() = 'COMPLIANCE_OFFICER' THEN VAL
         ELSE '***-**-' || RIGHT(VAL, 4)
    END;

CREATE OR REPLACE MASKING POLICY MASK_ACCOUNT AS (VAL STRING) RETURNS STRING ->
    CASE WHEN CURRENT_ROLE() = 'COMPLIANCE_OFFICER' THEN VAL
         ELSE 'ACT-****'
    END;

ALTER TABLE SILVER_BANK_TRANSACTIONS MODIFY COLUMN CLIENT_SSN SET MASKING POLICY MASK_SSN;
ALTER TABLE SILVER_BANK_TRANSACTIONS MODIFY COLUMN ACCOUNT_NO SET MASKING POLICY MASK_ACCOUNT;

USE ROLE NA_ANALYST;
USE WAREHOUSE COMPUTE_WH;
SELECT * FROM FINANCIAL_GOVERNANCE_DB.WEALTH_CORE.SILVER_BANK_TRANSACTIONS ORDER BY TXN_ID;

-- TASK 4: Row-Access Policy (RAP) Regional Isolation
USE ROLE ACCOUNTADMIN;
CREATE OR REPLACE ROW ACCESS POLICY RAP_REGION_POLICY AS (REGION_VAL STRING) RETURNS BOOLEAN ->
    CASE
        WHEN CURRENT_ROLE() = 'COMPLIANCE_OFFICER' THEN TRUE
        WHEN CURRENT_ROLE() = 'NA_ANALYST' AND REGION_VAL = 'NA' THEN TRUE
        WHEN CURRENT_ROLE() = 'EU_ANALYST' AND REGION_VAL = 'EU' THEN TRUE
        ELSE FALSE
    END;

ALTER TABLE SILVER_BANK_TRANSACTIONS ADD ROW ACCESS POLICY RAP_REGION_POLICY ON (REGION);

USE ROLE EU_ANALYST;
SELECT * FROM FINANCIAL_GOVERNANCE_DB.WEALTH_CORE.SILVER_BANK_TRANSACTIONS ORDER BY TXN_ID;

-- TASK 5: Secure Data Sharing & Clean Room Audit View
USE ROLE ACCOUNTADMIN;
GRANT CREATE VIEW ON SCHEMA FINANCIAL_GOVERNANCE_DB.WEALTH_CORE TO ROLE COMPLIANCE_OFFICER;

USE ROLE COMPLIANCE_OFFICER;
USE WAREHOUSE COMPUTE_WH;
USE SCHEMA FINANCIAL_GOVERNANCE_DB.WEALTH_CORE;

CREATE OR REPLACE SECURE VIEW SECURE_GOLD_EXTERNAL_AUDIT_SUMMARY AS
SELECT
    REGION,
    SUM(AMOUNT)          AS TOTAL_SETTLED_VAL,
    COUNT(*)             AS SETTLED_TXN_COUNT,
    ROUND(AVG(AMOUNT),2) AS AVG_SETTLED_AMOUNT
FROM SILVER_BANK_TRANSACTIONS
WHERE STATUS = 'SETTLED'
GROUP BY REGION
ORDER BY REGION;

GRANT SELECT ON VIEW SECURE_GOLD_EXTERNAL_AUDIT_SUMMARY TO ROLE COMPLIANCE_OFFICER;

SELECT * FROM SECURE_GOLD_EXTERNAL_AUDIT_SUMMARY ORDER BY TOTAL_SETTLED_VAL DESC;

-- TASK 6: End-to-End Governance Audit & Lineage Reconciliation
-- TASK 6: End-to-End Governance Audit & Lineage Reconciliation
USE ROLE SYSADMIN;
GRANT SELECT ON TABLE BRONZE_BANK_PAYLOADS TO ROLE COMPLIANCE_OFFICER;

USE ROLE COMPLIANCE_OFFICER;
SELECT
    (SELECT SUM(PAYLOAD:amount::NUMBER(18,2)) FROM BRONZE_BANK_PAYLOADS)      AS BRONZE_GROSS_TOTAL,
    (SELECT SUM(AMOUNT) FROM SILVER_BANK_TRANSACTIONS)                        AS SILVER_GROSS_TOTAL,
    (SELECT SUM(TOTAL_SETTLED_VAL) FROM SECURE_GOLD_EXTERNAL_AUDIT_SUMMARY)   AS GOLD_GROSS_TOTAL,
    (SELECT SUM(PAYLOAD:amount::NUMBER(18,2)) FROM BRONZE_BANK_PAYLOADS)
        = (SELECT SUM(AMOUNT) FROM SILVER_BANK_TRANSACTIONS)                 AS RECONCILED_FLAG;